### PR TITLE
Updated docker-compose.armhf.yml to use multi arch images

### PR DESCRIPTION
**Pull request by zeerorg**
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>

Updated docker-compose.armhf.yml to use multi arch images for prometheus and alertmanager. Addresses issue #1235 

## Testing
Checkout the PR and run deploy_stack.sh on an armv7 device (like raspberry pi). Everything would work smoothly.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [x] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
> Checkout the PR and run deploy_stack.sh on an armv7 device (like raspberry pi). Everything would work smoothly.

We'd want to know that auto-scaling continued to work. You can use `hey` from Lab 9 of the workshop to generate load.

Please could you also see the contributing guide on how to format commit messages so that they don't wrap? https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md#commit-messages

```
git commit --amend
```

**Comment by burtonr** [comment]
Hey @zeerorg just checking in to see if you've had a chance to review Alex's comment(s).

Could you please provide an update?

**Comment by zeerorg** [comment]
I did run the tests using hey on local docker, but not on raspberry pi.

**Comment by rgee0** [comment]
Derek close: armhf addressed in https://github.com/openfaas/faas/commit/9690987319a9906d2863c93eee8634f78e6aa0b6

**Pull request closed without merging**
