### PR TITLE
Add blog post by Amir Movahedi

### PR DESCRIPTION
**Pull request by Qolzam**
Signed-off-by: Amir Movahedi <amir.gholzam@live.com>

## Description

Added the blog post to the community file.

## How Has This Been Tested?

I have checked the change in my repo. The change is only on community.md file.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by saiyam1814** [comment]
LGTM
@alexellis can be merged

**Comment by alexellis** [comment]
LGTM @Qolzam, please could you just rebase it?

Please, please, please do not do a git merge :-) `git pull origin master --rebase` should do it.

**Comment by Qolzam** [comment]
Sorry @alexellis but for this case I did not `git merge`. Now I should the rebase before pull request? I understood last time merge had problem but this time no merge.

**Comment by alexellis** [comment]
You need to rebase to sync up with the master branch, please can you do that and use `git pull origin master --rebase` - `origin` may be replaced with whatever remote name you are using on `git remote -v`

**Comment by alexellis** [comment]
I've added the blog post myself. Thanks for the PR.

**Pull request closed without merging**
