### PR TITLE
Updated basic auth plugin faas provider

### PR DESCRIPTION
**Pull request by Karthik-13**
## Motivation and Context
https://github.com/openfaas/faas/issues/1355
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [x] My issue has received approval from the maintainers or lead with the `design/approved` label

## How Has This Been Tested?
Tested with `dep ensure`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for the PR

**Comment by Karthik-13** [comment]
Hey @alexellis this is a hacktoberfest PR could you please add the label as well.

**Comment by alexellis** [comment]
That's not required. https://hacktoberfest.digitalocean.com/details

**Comment by Karthik-13** [comment]
> That's not required. https://hacktoberfest.digitalocean.com/details

Got it. Thanks 👍

**Pull request merged**
