### PR TITLE
add link to blog describing how to write serverless crystal functions

### PR DESCRIPTION
**Pull request by TPei**
Signed-off-by: TPei <t.s.peikert@gmail.com>

I'd like to add a blog post I wrote on using Crystal with OpenFaaS to the community.md file

### CODE REVIEW

**Comment by burtonr** [comment]
Blog post looks good! Nice you added some additional details at the bottom about your setup for the comparison. Nice work!

**Comment by LucasRoesler** [comment]
I agree, the post looks nice and it reads well, but adding details about the server setup would be really good

**Comment by alexellis** [comment]
Thank you both for reviewing. Thomas could you look into making an update before we promote your post on twitter please?

**Comment by TPei** [comment]
As in general "how to set up OpenFaas" @LucasRoesler ?

**Pull request merged**
