### PR TITLE
Add new blog to community resources.

### PR DESCRIPTION
**Pull request by yankeexe**
Add [Deploy your Serverless Python function locally with OpenFaas in Kubernetes](https://dev.to/yankee/deploy-your-serverless-python-function-locally-with-openfaas-in-kubernetes-18jf) blog to `community.md`. 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by alexellis — DISMISSED** [review]
LGTM

**Comment by alexellis** [comment]
You'll need to rebase this.

**Comment by alexellis** [comment]
@yankeexe please see my comment above.

**Comment by yankeexe** [comment]
@alexellis  Can you check now? I tried rebasing, but it says my branch is up to date.

**Comment by alexellis** [comment]
Closing as I see no changes. Feel free to do a new PR if you have new posts to list.

**Pull request closed without merging**
