### PR TITLE
Added a message for people who don't have javascript enabled

### PR DESCRIPTION
**Pull request by Rillian-Grant**
## Description

I have added a CSS class that hides the element it is applied to if java script is disabled.
I have applied this to a div element containing all of the body code.
I have also added a message that is shown when java script is disabled.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: Rillian Grant <rillian.grant@hotmail.com>

### CODE REVIEW

**Comment by Rillian-Grant** [comment]
I also changed the JavaScript typo but I annoyingly forgot to sign it off, can you add that for me as I can't seem to edit it.

My sign off: Rillian Grant <rillian.grant@hotmail.com

**Comment by BurtonR** [comment]
@Rillian-Grant  You just need to ammend your last commit with your sign off:
`git commit --amend -s`

**Comment by Rillian-Grant** [comment]
Can I do that online I don't have access to my dev workstation at the moment.

**Comment by BurtonR** [comment]
Unfortunately, no. For that advanced git commands, you'll need a terminal...

**Comment by Rillian-Grant** [comment]
Ok sorry ill get to ti as soon as possible

**Comment by Rillian-Grant** [comment]
I've had multiple problems so I thought it would be best to open a new pull request.
You can find it here: [https://github.com/openfaas/faas/pull/659](https://github.com/openfaas/faas/pull/659)

**Pull request closed without merging**
