### PR TITLE
AfterBurn for Watchdog

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Fast Fork mode for the Watchdog enables a single process to be re-used over and over for an OpenFaaS function. 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md))

See notes at https://github.com/alexellis/faas/tree/fast_fork/watchdog and #114 

Test repo up for JVM function at - https://github.com/alexellis/java-openfaas-fast-fork

Video: https://www.youtube.com/watch?v=gG6z-4a1gpQ

## How Has This Been Tested?

With a Golang and Java function. Video demo in notes at #114 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by e-beach** [comment]
Is Fast Fork a synonym to  [AfterBurn](https://blog.alexellis.io/openfaas-serverless-acceleration/#afterburn)?

**Comment by genexp** [comment]
@e-beach It is.  Little confusing :)  Basically you move from a process that quits when complete, to one that stays active and can accept more requests.

**Comment by alexellis** [comment]
What is confusing? Have you guys read the README for this?

It's called AfterBurn because you can significantly increase thrust (throughput) at a cost of slightly more complexity. It's based upon an industry standard which never took off called FastCGI - i.e. we re-use the same process for as many requests as possible - thus allowing the JVM or whatever to optimize and ramp up.

**Comment by e-beach** [comment]
@alexellis Thanks. Just why is it called Fast Fork in this PR and AfterBurn in other places such as your blog post?

**Comment by rgee0** [comment]
@e-beach Mostly a timing thing.  The initial concept was referred to as fast fork, then once the concept had been proven and made it into the product it was branded as 'Afterburn'.

**Comment by alexellis** [comment]
Closing in favour of - https://github.com/openfaas/faas/pull/224

**Pull request closed without merging**
