### PR TITLE
Update community.md

### PR DESCRIPTION
**Pull request by affix**
## Description

Add my linkerd talk
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@affix please see feedback from Derek

**Comment by burtonr** [comment]
Hi there @affix! Are you able to address the `no-dco` issue on the commit? The comment from "derek" explains how to quickly correct it.

**Comment by affix** [comment]
Done @burtonr @alexellis

**Comment by alexellis** [comment]
Cheers both

**Pull request merged**
