### PR TITLE
Gateway UI - validate manual input

### LINKED ISSUE #901: Suggest: verify args when deploy a  new function
I suggest should to verify arguments  when our use `OpenFaas Portal` to deploy a new function

## Expected Behaviour

If args `Docker Image` or `Function name` is empty, `deploy` button should disabeld or show warning message , not send request to backend server 

## Current Behaviour

If arguments `Docker Image` or `Function name` is empty, can also send request get error

## Possible Solution

1. we can verify args when deploy a new function only `frontend`
2. we also verify args in `backend`

some screens as follow:

### PR DESCRIPTION
**Pull request by burtonr**
## Description

This change validates manual input to the gateway UI when deploying
new functions. This is to prevent poor user experience when attempting
to deploy a function manually from the UI.

The validation check on the function name is the same pattern that
is used in the CLI to ensure that when the deploy button is pressed,
the function will not fail validation.

Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
Fixes #901 

## How Has This Been Tested?

Deployed updated gateway code locally, and attempted to input good and bad input into the fields.
openfaas-input-validation

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by bartsmykla** [comment]
LGTM

**Comment by alexellis** [comment]
We are waiting on a reply to Ken from Burton before merging.

**Comment by burtonr** [comment]
@kenfdev the `maxlength` and `minlength` were existing properties on those fields. I left them there as I wasn't sure either where they came from... 

@alexellis What's your opinion? Should I remove those restrictions, or leave them as they were pre-existing?

**Comment by kenfdev** [comment]
Thanks for the response @burtonr ! I'd say this PR is gtg.  Whether we leave the `maxlength` or `minlength` or delete it, I think it could be a different issue and PR.
If there isn't a solid background to the `minlength` being `2`, let's delete it there.
cc @alexellis

**Comment by alexellis** [comment]
Thanks for replying on the last query. I've merged the PR. :+1:

**Comment by alexellis** [comment]
Can someone set the milestone to the next patch release?

**Pull request merged**
