### PR TITLE
Added a message for people who don't have JavaScript enabled. (2)

### PR DESCRIPTION
**Pull request by Rillian-Grant**
## Description

I have added a CSS class that hides the element it is applied to if java script is disabled.
I have applied this to a div element containing all of the body code.
I have also added a message that is shown when java script is disabled.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: Rillian Grant <rillian.grant@hotmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the contribution. We have reviewed the PR in the contributors call and will merge this PR.

**Comment by rgee0** [comment]
Should we be even more helpful and suggest a user who doesn't have javascript enabled might find similar functionality in the CLI, and show the curl command?

**Comment by Rillian-Grant** [comment]
Good idea. I'll include that.

**Comment by alexellis** [comment]
I'm testing your PR on my machine now with the CLI changes - thanks for responding to our feedback.

Please could you update the commit messages in line with our contribution guidelines? (We are also removing the (.) dot on the subject-line.

```
git reset HEAD~2
git add .
git commit -s
```

Type your message like this:

```
Add message for when JavaScript is disabled

- Added info about the CLI to the "You need JavaScript" page
- Added a message for people who don't have JavaScript enabled

Signed-off-by: Rillian Grant <rillian.grant@hotmail.com>
```

(See how we left a line blank - then added the body on the next line)

Then push with `--force`

```
git push origin master --force
```

**Comment by alexellis** [comment]
I tested this with Ivana and we had one more comment. This could be styled to look closer to the OpenFaaS UI theme (including some padding), but we will accept the current change and merge. Just update the commit messages for us please.

screen shot 2018-04-24 at 2 40 19 pm

**Comment by Rillian-Grant** [comment]
Done, sorry about the wait.
I'll try to be quicker in the future.

**Comment by alexellis** [comment]
Is the username correct? It says root at the moment?

**Comment by Rillian-Grant** [comment]
Oh that's OK I just spun up a VPS to do it. Do you want me to change it?

**Comment by Rillian-Grant** [comment]
Fixed it.

**Comment by Rillian-Grant** [comment]
I've added 15px padding

**Pull request merged**
