### PR TITLE
Added blog post for my first PR to OpenFaaS

### PR DESCRIPTION
**Pull request by BurtonR**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Please place in the correct date order and then sign off. Cheers 👍

**Comment by BurtonR** [comment]
This was an update from Github.com, so no opportunity to sign. I'd fixed the order (sorry I missed that!) and created a new (signed) PR https://github.com/openfaas/faas/pull/281

**Comment by johnmccabe** [comment]
@BurtonR as an FYI - you can manually sign by just pasting the signature text into the commit message if you're working directly from the webpage

**Comment by BurtonR** [comment]
Good to know! Thanks for the tip!

**Pull request closed without merging**
