### PR TITLE
Update samples.yml 

### PR DESCRIPTION
**Pull request by vichitr**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ `x`] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [`x` ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [`x` ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [`x` ] I have updated the documentation accordingly.
- [`x` ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
git commit -s

### CODE REVIEW

**Comment by vichitr** [comment]
git commit -s

**Comment by vichitr** [comment]
Derek! Where should I write this command "git commit -s"?

**Comment by rgee0** [comment]
Please review the contributing guide: https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md

**Comment by alexellis** [comment]
If the docker image names are valid, then let's not change them because I will have pushed all the images to the Hub already and that would mean me having to go through and delete them all. Thanks for the work so far 👍

**Comment by alexellis** [comment]
It's mainly the function name that was causing us issues at deployment time.

**Comment by alexellis** [comment]
@vichitr I'm going to close due to inactivity. Please feel free to raise again with the suggestions made above.

**Pull request closed without merging**
