### PR TITLE
Bumped version of faas-swarm to 0.6.1 and gateway to: 0.9.14

### PR DESCRIPTION
**Pull request by bartsmykla**
I changed the version of image to current one,
which implements secret management endpoint (https://github.com/openfaas/faas-swarm/pull/42)
from 0.5.0 to 0.6.1 in docker-compose.yml (x86_64)

Also version of gateway was bumped from 0.9.11 to 0.9.14 (x86_64)

Signed-off-by: Bart Smykla <bsmykla@vmware.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I fired `./deploy_stack.sh` on my local machine

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Can you do me a quick favor before I merge this? It's OK if you do it tomorrow.

Create a secret using CURL then list and delete it via the CLI and paste the output here.

Thanks,

Alex

**Comment by bartsmykla** [comment]
I'm on it now, one sec

**Comment by bartsmykla** [comment]
```
➜  ~ docker secret ls
ID                          NAME                  DRIVER              CREATED             UPDATED
pd9n452sxbd7a8hovu8zro2ui   basic-auth-password                       2 days ago          2 days ago
ekw7mkxk06ydo9qs03u7qq0lg   basic-auth-user                           2 days ago          2 days ago
yl71oi13rxe30gh3izfapu778   test3                                     2 days ago          2 days ago
➜  ~ curl -d '{"name":"foo","value":"test"}' -X POST http://localhost:8080/system/secrets
➜  ~ docker secret ls
ID                          NAME                  DRIVER              CREATED             UPDATED
pd9n452sxbd7a8hovu8zro2ui   basic-auth-password                       2 days ago          2 days ago
ekw7mkxk06ydo9qs03u7qq0lg   basic-auth-user                           2 days ago          2 days ago
xi8d447xpp7i2uqppq52hf5id   foo                                       4 seconds ago       4 seconds ago
yl71oi13rxe30gh3izfapu778   test3                                     2 days ago          2 days ago
➜  ~ curl -X GET http://localhost:8080/system/secrets
[{"name":"foo"},{"name":"test3"}]%                                                                                                 ➜  ~ curl -d '{"name":"foo"}' -X DELETE http://localhost:8080/system/secrets
➜  ~ curl -X GET http://localhost:8080/system/secrets
[{"name":"test3"}]%                                                                                                                ➜  ~ curl -d '{"name":"test3"}' -X DELETE http://localhost:8080/system/secrets
➜  ~ curl -X GET http://localhost:8080/system/secrets
null%
```

**Comment by alexellis** [comment]
This doesn't look right:

```
curl -X GET http://localhost:8080/system/secrets
null
```

**Comment by bartsmykla** [comment]
I'm checking it

**Comment by alexellis** [comment]
The operator has the same issue @stefanprodan @LucasRoesler of giving `null` when we have no secrets in the list.

**Comment by bartsmykla** [comment]
@alexellis There is a PR for that change: https://github.com/openfaas/faas-swarm/pull/44

**Comment by alexellis** [comment]
Release ready if you want to bump up your version: https://github.com/openfaas/faas-swarm/releases/tag/0.6.1

**Comment by bartsmykla** [comment]
I'm on it

**Comment by bartsmykla** [comment]
@alexellis I bumped the version of faas-swarm and also bumped the gateway to `0.9.14`

**Comment by alexellis** [comment]
Do we have a CI error @bartsmykla ?

**Comment by bartsmykla** [comment]
@alexellis My bad. It's fixed now

**Pull request merged**
