### PR TITLE
Fixed not visited static resources

### PR DESCRIPTION
**Pull request by feifeiiiiiiiiiii**
We need to download static resources to repository

Signed-off-by: qinpengfei <qinpengfei@jd.com>

## Description

`ajax.googleapis.com` blocked cann't visited  openfaas ui

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@kenfdev @bartsmykla @burtonr please can you share your thoughts on above?

Alex

**Comment by alexellis** [comment]
Thanks for the patch @feifeiiiiiiiiiii 

@kenfdev please can you confirm the content added here matches the original versions before we move any further forward?

Alex

**Comment by kenfdev** [comment]
Thank you for the contribution @feifeiiiiiiiiiii 

I'd say it's a reasonable move. We don't have to rely on CDN much.

> please can you confirm the content added here matches the original versions before we move any further forward?

I've confirmed the files match the original version.

Things I have in mind:

* I'd like to know if this has been tested. (Please don't leave "How Has This Been Tested?" blank)
* I'd prefer the directory names to match the original. Meaning `script/angularjs` rather than `script/angular.js` and `script/angular_material` rather than `script/angular-material`.  A matter of preference though!

**Comment by feifeiiiiiiiiiii** [comment]
@kenfdev I will to modify follow you suggest
Thanks very much

**Comment by alexellis** [comment]
@kenfdev ping

**Comment by kenfdev** [comment]
Thank you @feifeiiiiiiiiiii !
LGTM.
This fix will help people who can't reach the CDN.

**Comment by feifeiiiiiiiiiii** [comment]
@alexellis 
I think you can use other CDN (eg: you suggest use GithHb's CDN) to solve this issue

**Pull request closed without merging**
