### PR TITLE
Fixes #245 Added os.TempDir() to replace using '/tmp/'

### LINKED ISSUE #245: Multi-platform: Use tempdir() from Golang instead of /tmp
This is a change for the watchdog.

We write a lock-file to `/tmp/` and have to disable it for Windows (via `suppress_lock`) since it is an invalid path. If we use Golang's tempdir() method in `os` then we should never need to use the `suppress_lock` configuration.

### PR DESCRIPTION
**Pull request by fharding1**
## Description
This PR fixes issue #245 of the lock file not being crossplatform because of just using '/tmp/'. os.TempDir() is used to find a temporary dir, completely crossplatform. ~~Because of this, suppressLock is no longer needed and has been removed.~~

## Motivation and Context

- [x] @alexellis has raised an issue to propose this change ([required](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I built the code, ~~removed the tests for supressLock and the parts of suppressLock in the config since it's not needed,~~ also tested the `filepath.Join(os.TempDir(), ".lock")` code on a Windows and Linux computer, and the actual fwatchdog file on Windows and Linux.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) (sorta)?
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation. (unsure about this)
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes. (unsure)
- [ ] All new and existing tests passed.

I'm fairly new to collaborating and commiting to projects so please LMK if I did anything wrong. I don't believe new tests are needed as well but am unsure, as well as with docs.

### CODE REVIEW

**Comment by alexellis** [comment]
Ok - we'll need the commit to be signed and pushed again. Have you tested on Windows or a Windows VM?

**Comment by alexellis** [comment]
Please retain suppress_lock in the code for now too.

**Comment by fharding1** [comment]
Okay signed and pushed again, also retained the suppressLock code. I tested it on a windows VM. I got the path: `C:\Users\franklin\AppData\Local\Temp\.lock` from this: `fmt.Println(filepath.Join(os.TempDir(), ".lock"))`

**Comment by alexellis** [comment]
+1 for testing. Was that testing through the watchdog binary? i.e. `GOOS=windows go build -o fwatchdog.exe`.

Then:

```
C:\> set fprocess=ipconfig.exe
C:\> ./fwatchdog.exe
```

Then visit http://localhost:8080 or use `curl` in Git bash/WSL:

```
$ curl localhost:8080
```

**Comment by alexellis** [comment]
Btw for future reference, it's better to do a `git checkout -b PR_NAME_ETC` before adding changes and raising a PR. This helps us with testing the changes and means your own `master` branch can stay clean/in-sync with us.

**Comment by fharding1** [comment]
Ah okay, I thought making a new branch was only if you were going to do multiple PRs (one branch per PR), thanks for letting me know you should always do it even with one. That testing was just on that line of code and not the actual binary, but now I have tested the binary via your instructions and it seems to work fine on Windows. Attached is both the output from cmd and the webpage served at http://localhost:8080, seems to work fine.

[U0U7A65D.txt](https://github.com/openfaas/faas/files/1347343/U0U7A65D.txt)
[cmdoutput.txt](https://github.com/openfaas/faas/files/1347344/cmdoutput.txt)

**Comment by fharding1** [comment]
Actually just figured out this doesn't seem to work right on Linux, will fix ASAP.

**Comment by fharding1** [comment]
Okay it now is confirmed working on both Linux and a Windows VM (the actual watchdog file). It creates the lock file as '(tempdir)/.lock'.

**Comment by alexellis** [comment]
Pushing to `master` for a PR can be problematic, it makes `git pull` (which maintainers use to test a change out locally) quite hard. 

https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by alexellis** [comment]
Great to hear that. Testing changes means PRs can get merged faster 👍 LGTM

**Pull request merged**
