### PR TITLE
Added Adopter entry Rapid Circle

### PR DESCRIPTION
**Pull request by therealburningman**
## Description
added quick use case.

## Motivation and Context
as requested

## How Has This Been Tested?
reading

## Types of changes
comment

### CODE REVIEW

**Comment by therealburningman** [comment]
> Lgtm. Could you follow the instructions from Derek on the commit?

Sure! I executed those sign off and forced push commands.

**Comment by therealburningman** [comment]
> Lgtm. Could you follow the instructions from Derek on the commit?

@alexellis I did as requested. Or ?

**Comment by alexellis** [comment]
> Tip: if you only have one commit so far then run: git commit --amend --signoff and then git push --force.

**Comment by alexellis** [comment]
@therealburningman PTAL

**Comment by alexellis** [comment]
@therealburningman could you send us a quick email to support@openfaas.com just stating that you're happy for Rapid Circle to be listed? Thanks.

**Pull request closed without merging**
