### PR TITLE
Afterburn 0.1 for watchdog

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Afterburn mode for the Watchdog enables a single process to be re-used over and over for an OpenFaaS function.

## Motivation and Context

- [#114] I have raised an issue to propose this change ([required](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md))

See notes at https://github.com/openfaas/faas/tree/afterburn_01/watchdog and #114

Client libraries:

* [JVM / Java](https://github.com/alexellis/java-openfaas-fast-fork)
* [Python 2.7](https://github.com/alexellis/python-openfaas-fast-fork)
* [Node.js](https://github.com/alexellis/nodejs-afterburn)

Video: https://www.youtube.com/watch?v=gG6z-4a1gpQ

## How Has This Been Tested?

With a Golang, Java, Python and Node.js functions. Video demo in notes at #114

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Ping @JockDaRock

**Comment by alexellis** [comment]
Derek add label: status/testing

**Comment by alexellis** [comment]
Merging subject to CI passing.

**Comment by trusch** [comment]
Just a note on this implementation: It would be nice to be able to choose other framing formats than HTTP. Obvious other formats would be line-framing or JSON.

**Comment by alexellis** [comment]
For each format we have to write and maintain a client library for every language. HTTP is the easiest to parse and has proven itself to handle binary data well also. Once we have good support for a batteries-included language it's unlikely we will need others unless they have significant pros.

**Comment by alexellis** [comment]
Closing in favor of https://github.com/openfaas-incubator/of-watchdog

**Pull request closed without merging**
