### PR TITLE
Add Waylay to ADOPTERS.md

### PR DESCRIPTION
**Pull request by SanderVanhove**
## Description

Added Waylay as one of the adopters of OpenFaas.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Non-functional

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR @SanderVanhove 🙂 

Can you run the command from Derek?

**Comment by alexellis** [comment]
@SanderVanhove let us know when you've fixed the PR :+1:

**Comment by SanderVanhove** [comment]
Sorry, had some other things to take care of. It should be signed now @alexellis 😁

**Comment by alexellis** [comment]
Great. After you run the first command, do the git push with --force after that and Derek will remove the label

**Pull request merged**
