### PR TITLE
[GH-1167] update dockerfile to add user - sample-functions/ApiKeyProtected-Secrets

### PR DESCRIPTION
**Pull request by cpanato**
## Description
Update dockerfile to use the latest template adding a non root user

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi is there anything preventing us from switching this sample to using the OpenFaaS Go template? 

Alex

**Comment by cpanato** [comment]
based on the discussion in the openfaas community removing the code and redirecting to the other sample

**Comment by cyber99999** [comment]
#blcr

**Comment by alexellis** [comment]
Merged. Please check there are no broken links in the docs.

**Pull request merged**
