### PR TITLE
Added ability to edit metadata in the UI

### PR DESCRIPTION
**Pull request by padiazg**
Signed-off-by: Patricio Díaz <padiazg@gmail.com>

Added a button wich shows **labels** and **annotations** for the selected function, also allows basic editing (add & delete)

## Description
A new button next to the Delete function was added. 
It displays a popup with a tabbed view, one tab for ```Labels``` and another for ```Annotations```.
There are fields for ```Key``` and ```Value``` which both should be filled to add a new label or annotation.
Every element can be deleted using a button next to the value.
If a value matches for an url, a button to open it in a new window/tab is displayed.

## Motivation and Context
Fixes issue #870 
https://github.com/openfaas/faas/issues/870

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Copied the prosed code into the gateway container using
```
$ cd faas/gateway/
$ sh -c "docker cp assets $(docker ps -qf \"name=func_gateway\"):/home/app/"
```
Tested adding and deleting values, checking function data after each operativon using Rest calls to the API. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @padiazg thanks for this PR. The UI is mainly under a code-freeze at the moment so I am cautious about adding features, but if you can provide some screenshots and a GIF/YouTube screen recording we could review the feature in the community.

Alex

**Comment by padiazg** [comment]
During the video recording, found something that's not working. I'll rise an issue about it, and after that is resolved I will resume this.

**Comment by padiazg** [comment]
Here is a video to show how it works.
[OpenFaaS Portal metadata edit](https://youtu.be/7pAY_7nxdPk)

There is the way to add urls to point to source/examples/docs. I'm currently working on monitoring if there is a `com.openfaas.sample_payload` annotation and copy it's value to the request body as a tip on how the function should be called.

Also I think that if there is a annotation like `com.openfaas.function_tips` or `com.openfaas.function_help` or just `com.openfaas.help`, we should show it's value somewhere near the "Invique function" card.

**Comment by ivanayov** [comment]
We talked about migrating the UI to React. May be this should go in before those changes so that the PR will not need to be fully rewritten?

**Comment by padiazg** [comment]
At the moment that I wrote this, my idea was to have the ability to add metadata like the source repository, or a link to the help, also I was wondering if we could make possible to change the autoscaling values from the UI, updating the corresponding labels.

After that came the idea for adding an specifically named annotation on MD format with a short help, so the UI can identify it and show it when the function is selected. It could contain for example the parameters or an example of the payload, maybe a link to a more extensive documentation. 

If you think this is interesting I'll keep working on this, but I think we have to agree first the roadmap of the UI, is it frozen yet or can accept new features, are we moving to another framework?.

**Comment by bartsmykla** [comment]
@padiazg everything looks like we'll be moving to react in very close future

**Comment by alexellis** [comment]
Hi @padiazg I don't think either of us have the bandwidth to finish this work. Thanks for your help, let me know things change. 

Alex

**Pull request closed without merging**
