### PR TITLE
Updates faas-swarm to current release 6.2

### PR DESCRIPTION
**Pull request by ewilde**
Signed-off-by: Edward Wilde <ewilde@gmail.com>

## Description
Update faas-swarm to latest release 6.2 in docker-compose

## Tested
image

image

image

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Ed, ARM builds are manual.

I'll kick off an ARMHF build, which should be up in a few minutes, please confirm you can pull the image before giving me the go-head.

For ARM64 revert the change since I won't be able to do the build immediately. 

Alex

**Comment by alexellis** [comment]
@ewilde

**Comment by ewilde** [comment]
@alexellis PTAL

**Comment by alexellis** [comment]
LGTM, thanks

**Pull request merged**
