### PR TITLE
[Revisit/review] Refactor gateway to allow metrics other than Prometheus

### PR DESCRIPTION
**Pull request by nicholasjackson**
Updated logger to be a little more configurable
Refactored gateway main function
Added replicas package to Dockerfile
Refactor
Updated documentation

Signed-off-by: Nic Jackson <jackson.nic@gmail.com>

## Description
Refactored the gateway to allow pluggable metrics backends extending the use beyond Prometheus.  I have also started to refactor the code to improve readability in gateway/server.go
At present I have implemented the StatsD protocol for metrics, this allows data to be sent to many SaaS based systems such as DataDog.

## Motivation and Context
Supporting only one metric collection endpoint limits the deployable scope for OpenFaaS and does not accommodate users who do not use Prometheus in their production systems.

https://github.com/openfaas/faas/issues/441
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Tested locally using prometheus and on AWS using the StatsD output, both appear to be performing correctly however a second opinion on the Prometheus metrics would be appreciated.

A build can be found at [https://hub.docker.com/r/nicholasjackson/gateway/](https://hub.docker.com/r/nicholasjackson/gateway/) which can be used for testing.  This is only a Linux build and will not work on Arm.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi Nic, I appreciate this could be useful to the nomad implement but all PRs need to follow contribution guide of a design proposal and review.

**Comment by nicholasjackson** [comment]
It is a generic pull request to implement features other than Prometheus it has nothing to do with Nomad

**Comment by alexellis** [comment]
Nic I appreciate your contributions to the wider OpenFaaS project and what you're doing in the community too. I wanted to let you know that I’m going to close the statsd / gateway PR. Let’s have a think about how to cover alternative metrics in the next contributor meeting - ideally in a way that doesn’t need to alter as much code in the gateway service. If/when we get to something let's also go through the proper process of raising an issue for design / review and then moving forward afterwards.

**Comment by tmelman** [comment]
Is there any progress on this front? This remains a useful extension.

**Pull request closed without merging**
