### PR TITLE
Add Oli's & my talk/blogs to community.md

### PR DESCRIPTION
**Pull request by developius**
## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Can merge when signed 👍 thanks

**Comment by developius** [comment]
It is...?

**Comment by rgee0** [comment]
Are you sure?

**Comment by developius** [comment]
Github says it's "verified"

**Comment by rgee0** [comment]
As I understand it:
`-S` verifies that you committed it
`-s` is more about you certifying that you created the content and it falls in line with the licensing, etc

**Comment by developius** [comment]
Cheers for the help @rgee0, I've learnt some more about git 😁
Good to go @alexellis

**Pull request merged**
