### PR TITLE
Adding Azure Blog Post and Azure Storage Queue Trigger Repo

### PR DESCRIPTION
**Pull request by danigian**
Signed-off-by: Daniele Antonio Maggio <dcharizard@gmail.com>

### CODE REVIEW

**Comment by alexellis** [comment]
Somehow managed to get a merge conflict.. can you check it out?

**Comment by alexellis** [comment]
Ping @danigian

**Comment by danigian** [comment]
Everything done from my side. Please double check 👍

**Comment by alexellis** [comment]
All commits need to be signed off. I'm getting an error here from GitHub

> This branch cannot be rebased due to conflicts

Might be easier to close and submit a fresh PR.

**Pull request closed without merging**
