### PR TITLE
Updated the NodeJS sample functions to use the latest LTS versions. F…

### PR DESCRIPTION
**Pull request by BurtonR**
…ixes #383

Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

## Description
Upgraded NodeJS version in sample-functions

## Motivation and Context

NodeJS 8.9.1 is now LTS

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Built the sample functions with NodeJS 8.x features and deployed to a local OpenFaaS swarm

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.

The `samples.yml` in the sample-functions directory uses the images from the functions repository on Dockerhub. These will need to be rebuilt and re-pushed in order to be upgraded with this new version.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for the PR. Changing this takes me much longer as it needs me to go into the Docker Hub.

**Comment by austinfrey** [comment]
tested these changes by building locally and deploying. no issues. LGTM

**Comment by BurtonR** [comment]
I with you @alexellis. The templates are pretty much the sample functions. No need to maintain both!

All my hard work...gone! :frowning_face:  haha!

**Comment by johnmccabe** [comment]
+1 on nuking the images..

that said if you want images automatically updated/pushed on tag then thats something that could be done...

**Pull request closed without merging**
