### PR TITLE
Display client-round-trip time in seconds in the UI

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Display client-round-trip time in seconds in the UI

## Motivation and Context

Useful for understanding latency / duration for various functions. Note this reflects client trip-time, not function execution time which is recorded in Prometheus

## How Has This Been Tested?

screen shot 2017-11-17 at 16 53 11

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ericstoekl** [comment]
Looks awesome!!

[Here's a screenshot of it working for me](https://kek.gg/i/7hN-8p.png)

**Comment by JockDaRock** [comment]
Yep looks good! working great

**Comment by JockDaRock** [comment]
https://s7.postimg.org/nnxxh3fgr/round_trip_test.png

**Comment by alexellis** [comment]
Great, thank you for trying it out

**Comment by developius** [comment]
Nice one @alexellis!

**Pull request merged**
