### PR TITLE
Fixed broken IE behavior

### PR DESCRIPTION
**Pull request by kenfdev**
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>

## Description

The current gateway UI wasn't working on IE11. (It was completely a blank page for me)
I looked at the error and found some ES6 arrow function syntax in the uuidv4 function.
I fixed it to use normal `function` syntax.

In addition, after being able to see the UI again, I found that the layout wasn't working well with IE11, too. Found that the HTML didn't have a proper closing tag, hence the layout didn't work well.
(probably other browsers auto-fix these problems)

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
#537 

## How Has This Been Tested?

* IE11
* Chrome 63.0.3239.132

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kenfdev** [comment]
Here's the screenshot of the broken layout.

Before
ss 2018-02-27 23 15 03

After
ss 2018-02-27 23 19 50

**Comment by kenfdev** [comment]
I don't have time now so testing on other browsers would help. (or I can do it later this week)

In addition, there are more issues on IE11 that I found.
There is no `crypto` object. (fyi https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto)

We need to change the way `trydownload` works. The current implementation doesn't work on IE11.
Will create an issue tomorrow.

**Comment by alexellis** [comment]
Hey @kenfdev thank you so much for making time to work on this.

Let me respond to the three fixes/issues here:

* Removed ES6 arrow syntax ✅ 

Thank you

* Broken tag  ✅

I could imagine this was affecting edge too - which looked odd.

* The `crypto` object ❓

> There is no crypto object. (fyi https://developer.mozilla.org/en-US/docs/Web/API/Window/crypto)

I had a quick read of that page. It might exist, but be prefixed.

screen shot 2018-02-27 at 3 23 44 pm

**Comment by dungeonmaster18** [comment]
Hey @kenfdev I was testing this but it's still not working. I deployed it on pwd it worked on all the other browsers but it didn't on IE. And also it shows the same error as of the previous.
P.S As the initial use case for the issue was to deploy it on some remote server and test it on IE.
screenshot 9

CC / @alexellis

**Comment by alexellis** [comment]
I've leave the two of you to collaborate on this, let me know if you need me.

**Comment by kenfdev** [comment]
Thanks @dungeonmaster18 !
Hmm, that's strange. Just to make sure but are you testing this on `kenfdev:fix-ie` branch?
And have you force refreshed IE (ctrl + f5)?

Also, if you look at the source code,  does it look like the following:

```
return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, function(c) {
```

not

```
return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
```

**Comment by dungeonmaster18** [comment]
sorry my bad I didn't change the docker-compose to use gateway:latest-dev. It works now perfectly.

**Comment by kenfdev** [comment]
Awesome @dungeonmaster18 ! Thanks for pointing out the other missing closing tag, too.

Also, I've noticed a missing `return` statement so added that as well.
Retested with

* Chrome
* Safari
* Firefox
* IE11

**Comment by alexellis** [comment]
Please make the fix re: the IE prefix in a follow-up PR if required.

Merging now.

**Pull request merged**
