### PR TITLE
Feature: Add min/max scale for auto-scaling - Swarm & external providers 

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Feature: Add min/max scale for auto-scaling - Swarm & external providers 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

See: #414 

## How Has This Been Tested?

With new tests and with Stefan via gateway and kubernetes

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ericstoekl** [comment]
Tried this out and at least can see that `min` is working, as the number of replicas for my function starts at 5. What's the recommended way to make the container scale up until it hits its `max` limit? Would using `ab` work?

**Comment by alexellis** [comment]
Yes that will work too with a high number or a bash loop. Doesn't need to be high figures for concurrency and you can monitor the alerts in Prometheus too

**Comment by ericstoekl** [comment]
Gotcha, I will try that out.

I have tried to load this up on Kubernetes (uploaded the gateway image to docker hub, then set the gateway definition in `faas.yml` to load that image), and it looks like my function has the min=5 and max=15 labels set, but it only has one replica when deployed. Would this be expected to work on faas-netes, or would more work be needed first?

**Comment by stefanprodan** [comment]
@ericstoekl this how Kubernetes works, replicas refer to pods not containers

**Comment by alexellis** [comment]
@ericstoekl  do this instead - `kubectl get deploy` that is where the replica count is stored.

**Comment by ericstoekl** [comment]
In that case, I see that the function has the correct number of replicas. Thanks 💯

**Comment by alexellis** [comment]
Thank you both for testing. I'll merge.

**Pull request merged**
