### PR TITLE
[WIP] Enable GET method for functions

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Enable GET method for functions. This is work in-progress and may need review - i.e. to allow functions to opt out of this method whether it causes them to block or wait for input.

Todo:
* [ ] Certify incubator tests https://github.com/openfaas/certify-incubator
* [ ] Opt-out mechanism
* [ ] Support mechanism for definition via environment or labels re: #178 

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

User request for "GET" support. Also asked for by @JockDaRock for Flask/Express support.

## How Has This Been Tested?

Tested in a web-browser and on the command-line, also benefits from fixes in #318

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Additional testing and tyre-kicking appreciated.

### CODE REVIEW

**Comment by alexellis** [comment]
Ideally we are going to need a way of disabling this for functions or allowing them to opt-in via a mechanism such as a label.

```
 labels:
  method_get: enabled
  get: enabled
```

**Comment by alexellis** [comment]
@JockDaRock - Flask / Express etc ?

**Comment by JockDaRock** [comment]
this does not appear to work as far as I can see... maybe I am doing this wrong

Will test some more

**Comment by JockDaRock** [comment]
GET method was not being passed along to watchdog request so the environment variables were not being picked up on the flask side.

on line 144 of proxy.go
`request, err := http.NewRequest(method, url, bytes.NewReader(requestBody))`

corrected this with a method variable that will pass along the method
```
method := r.Method
request, err := http.NewRequest(method, url, bytes.NewReader(requestBody))
```

Will make a pull request to add in the changes.

**Comment by JockDaRock** [comment]
comparison

https://github.com/openfaas/faas/compare/enable_get_method...JockDaRock:enable_get_method

**Comment by JockDaRock** [comment]
will also make commits and and a pull request for flask in the main functions as well as pull requests for routing through flask and express functions.

**Comment by alexellis** [comment]
This just maps GET to POST at the moment.

**Comment by alexellis** [comment]
@JockDaRock let's move here.

**Comment by kenfdev** [comment]
@JockDaRock Is there an example I can test this with?
I
* switched to the `enable_get_method` branch
* ran `build.sh`
* deployed with `gateway:latest-dev`
* created a function via `faas-cli new` (node.js)

and then I invoked with `POST` and it worked as normal. But with `GET` the request freezes.

For the function, in `template/node/index.js` I added a log at the beginning.

```
getStdin().then(val => {
    console.log("received request"); // added log here
    handler(val, (err, res) => {
        if (err) {
            return console.error(err);
        }
        if(isArray(res) || isObject(res)) {
            console.log(JSON.stringify(res));
        } else {
            process.stdout.write(res);
        }
    });
}).catch(e => {
    console.error(e.stack);
});
```

If it is a `POST` request, the log for the function container looks like this:

```
2017/11/03 11:13:25 /function/func_broker
received request
{"status":"done"}
```

But if it is a `GET` request, the log stops:

```
2017/11/03 11:14:05 /function/func_broker
```

So the function isn't being invoked.
If it's working with your environment, I've probably messed up something in my environment.
Thanks in advance!

**Comment by JockDaRock** [comment]
@kenfdev Let me take a look at your problem... I want to confirm this from my fork of enable_get_method and see if there is a problem on that end.

**Comment by alexellis** [comment]
We produced the issue by running the function in its own container directly on my host without a gateway. The code in the Node.js template requires some input on stdin, that's why it's failing. You could tweak the template for Node.js and keep moving forward.

**Comment by alexellis** [comment]
Changes pushed here fix the issue of hanging while waiting for `stdin` and will enable us to make functions to respond to bots such as Facebook where GET/POST is required for hand-shakes.

**Comment by kfukuyama** [comment]
@JockDaRock @alexellis 
Thanks for the responses. I'll need a little time but will definitely check it out with Facebook to see if it works.

**Comment by alexellis** [comment]
Released as 0.6.9 for the gateway Docker image and the watchdog. Both need upgrades.

**Pull request merged**
