### PR TITLE
* Added function store feature to the "Deploy New Function"

### PR DESCRIPTION
**Pull request by kenfdev**
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>

### Major Change
 * This feature fetches function catalogs from openfaas/store and makes
  one-click deploy easy
  * You can switch between "From Store" or "Manually" by tabs

### Minor Chnge
* Added icon to "Deploy New Function" button
* Added function search feature to the main UI
* Moved AngularJS templates to a `templates` folder (because it's starting to get cluttered)

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

This new feature lets people easily deploy functions from predefined community driven stores (from openfaas/store).

## How Has This Been Tested?

I've deployed normally, and via function store and tested invoking functions via UI.
All work as expected.

(Some more tests from others would be welcome :) )

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

func_store

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kenfdev** [comment]
@Razesdark Thank you for trying it.  Hmm... This didn't happen with me (firefox 54). Maybe it has something to do with cache??

In the mean time, firefox has a nasty layout right now...
image

I'll have to look in to this as well

**Comment by kenfdev** [comment]
@rorpage I assume the old JavaScript is present and still trying to find the old template...

**Comment by Razesdark** [comment]
@kenfdev I pulled down your PR again and rebuilt it and it works fine now!
I also get the same text placement as you though!

My tab bar is also filling the screen to the right, like this.
tab bar

**Comment by kenfdev** [comment]
@Razesdark Thank you! Yes, I've noticed that. Didn't expect Firefox to be this different. Will look in to it

**Comment by kenfdev** [comment]
I've reverted the fixed tabs and fixed the strange search input layout on firefox.
Here's a gif tested with firefox.

funcstore

**Comment by rorpage** [comment]
Just checked the styles for FF 57, Chrome 62, and Safari 11 and everything looks :+1:. I also deployed the `youtube-dl` function locally through the Store.

**Comment by rorpage** [comment]
Tested on Chrome on my phone and everything looked and worked great

**Comment by Razesdark** [comment]
Same here for FF57 on Linux. Works like a charm, none of the graphical bugs are present.

**Comment by JockDaRock** [comment]
This works for me on Safari, Firefox, and Chrome.  Great work!

**Comment by developius** [comment]
Wow this is awesome @kenfdev!

**Comment by alexellis** [comment]
Merging and releasing as 0.6.13 ... go grab it in a few minutes and share your screenshots with the community :tada:

**Pull request merged**
