### PR TITLE
Add PITS Global Data Recovery Services to the adopters list

### PR DESCRIPTION
**Pull request by pheianox**
## Description
This pull request adds new entry in the adopters list

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alexellis** [comment]
Hi can you also tell us the use case please? 🙂

**Comment by pheianox** [comment]
Dear @alexellis ,

Thank you for your comment on the pull request! Your feedback is greatly appreciated, and I wanted to address your question.

By adopting OpenFaaS, your company can optimize its operations and achieve greater efficiency. With the help of event-driven functions and microservices, you can streamline processes and improve scalability. OpenFaaS offers auto-scaling capabilities, allowing you to allocate resources dynamically based on demand. Additionally, the built-in metrics provide valuable insights for monitoring performance and driving continuous improvement.

Best regards,
@pheianox

**Comment by alexellis** [comment]
Thanks for the kind words.

How are you using openfaas at PITS?

The answer given sounds like it came from an AI or was generated, so I want to make sure this isn't spam or an advert.

**Comment by alexellis** [comment]
@pheianox please could you respond?

**Pull request closed without merging**
