### PR TITLE
Added a new blog entry to the community file

### PR DESCRIPTION
**Pull request by staal-it**
Added a new blog entry to the community file and fix then name of a previous one

## Description

Added a new blog entry to the community file and fix then name of a previous one

## Types of changes

Signed-off-by: Erwin Staal <info@staal-it.nl>

### CODE REVIEW

**Comment by alexellis** [comment]
Hi I gave you some feedback but I'm not sure if you saw it. If you could do a couple of things then I'm happy to merge this in.

1) Please explain the template store and add a link to the docs for it. 
2) Since you use build push and deploy separately, please mention and show how to use up which combines all three. 

How does that sound?

**Comment by staal-it** [comment]
Sure! Is this the link you are referring to? [https://docs.openfaas.com/cli/templates/#templates](docs)

**Comment by alexellis** [comment]
https://docs.openfaas.com/cli/templates/#template-store

Perhaps you could paraphrase the idea and concept. You could say how this would work with your new template and mention that there are at least two other dotnet core templates that can be found.

**Comment by staal-it** [comment]
Hi Alex, I've updated both the blogs. Please let me know what you think!

**Comment by alexellis** [comment]
I'll merge now, but there's a little bit of room for improvement.

When you do `faas-cli new --list` you're not looking at the `The template store`, so add a new heading for that called `Default templates`, then show cropped output from `faas-cli template store list`.

Thanks

**Pull request merged**
