### PR TITLE
chore: add log for easy debug

### PR DESCRIPTION
**Pull request by haozibi**
## Description

Just add logs to watchdog for easy debugging

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## How Has This Been Tested?

No tests are required

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
You should be able to get this logging by toggling one of the environment variables. 

Which ones have you tried? Did they work for you? https://github.com/openfaas/faas/tree/master/watchdog

**Comment by haozibi** [comment]
@alexellis hello

I have seen the environment variables of watchdog. When I debug the program, I enabled the `write_debug` environment variable in the program, but the watchdog will not output any error if it reads the error when reading the gateway request, let me think there is no problem, so I submitted this simple pr.

And I saw that there is no environment variable to open this error output.

**Comment by alexellis** [comment]
I am OK with the idea, but I'd like to see it as `write_debug_error` perhaps? Also is the error format consistent with the other messages?

**Comment by haozibi** [comment]
The error message is written in the format https://github.com/openfaas/faas/blob/b572e77471641091978cf97a030aaf88862eb212/watchdog/handler.go#L164-L168

I think adding an environment variable for simple log output is a bit complicated.

Do you have any good suggestions?

**Comment by alexellis** [comment]
I'm weary of adding additional log messages.

I guess my question would be, why did "buildFunctionInput" throw an error for you? How were you using it?

**Comment by haozibi** [comment]
I used a LoadBalance before the gateway. Due to the LoadBalance bug, the gateway sends the request to the watchdog very slowly. If the request body is very large, it may cause `io.readAll` to not read completely and then report the `unexpected EOF`. You can see this error (`error with upstream request to: , Post http://xxx.openfaas-fn.svc.cluster.local:8080: unexpected EOF`), but I can't see it explicitly in the watchdog. 

I just think that adding one will be more obvious, and the error returned by the gateway is a bit too simple.

**Comment by alexellis** [comment]
Sounds good to me. Thank you for explaining it.

**Comment by alexellis** [comment]
Thanks for your first PR. You're now a contributor and may appear on openfaas.com.

You can join Slack and chat with us more.

It would be great to understand more of what you're building and how you are using the project. We also have other areas where contributions are needed.

--
Join Slack to connect with the community
https://docs.openfaas.com/community

**Pull request merged**
