### PR TITLE
Config metrics endpoint

### PR DESCRIPTION
**Pull request by hxalid**
Make metrics endpoint configurable via 'metrics_endpoint'
environment variable. Default is '/metrics'.

Signed-off-by: Khalid Hasanov <xalid.h@gmail.com>

This change is a new feature making it possible to override gateway metrics
endpoint.  

## Description

This change is a new feature making it possible to override gateway metrics
endpoint. By using metrics_endpoint environment variable users can override
gateway metrics endpoints. The default value is '/metrics' which is the same as before.
 
## Motivation and Context

Not all Prometheus setups are configured to scrape '/metrics' endpoint and
therefore, this change would make it easier to have a consistent Prometheus 
config for different systems.

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/faas/issues/998

## How Has This Been Tested?

The change has been used with OpenFaaS Nomad plugin.

The tests were run by overriding 'metrics_endpoint' environment variable and 
making sure Prometheus can scrape the metrics.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Prometheus can be configured which endpoint it should scrape through configuration and through annotations when connected to tools such as Weave Scope. This change would not work for OpenFaaS on Kubernetes since we'd have to change the supporting configuration. OpenFaaS bundles its own Prometheus which is set up specifically to control metrics and scaling in a known way. 

Alex

**Comment by alexellis** [comment]
Derek add label: design/review

**Comment by alexellis** [comment]
Please also see our contribution guide which states you should not work on or submit a PR woehtour an approved issue first.

**Comment by hxalid** [comment]
Sorry not being clear in my previous explanations. This change is needed when there is an existing Prometheus setup that is not configured to scrape the default /metrics endpoint. I appreciate you pointed out links to Weave Scope. However, I'm not sure it would work in Nomad for instance. Also, I'm well aware that Prometheus can be configured to scrape different metrics endpoint, however, it is not convenient when Prometheus needs to be reconfigured for each new system that is being introduced into the existing infrastructure.

**Comment by alexellis** [comment]
In order to use OpenFaaS you will need to configure AlertManager and Prometheus separately. Having this configuration item doesn't make sense for our users at large and carries a cost of maintenance. 

The standard endpoint for Prometheus metrics is `/metrics`. Out of interest what is your system looking for and why?

**Comment by hxalid** [comment]
I totally agree with that. However, from my experience, where there is an existing Prometheus cluster that is configured to use a non-default metrics endpoint (for different reasons) it becomes necessary to override this setting at OpenFaaS.  There could be various reasons not to use a non-default scrape endpoint. For instance, we may have a load balancer in front of an existing Nomad cluster and when we hit the default endpoint it would get load balanced across different Nomad servers. However, it would make more sense if Prometheus scrapes a non-balanced specific endpoint. It is just one reason. If we are talking about a more complex established microservices infrastructure where all microservices by default expose metrics on a non-default endpoint, it would be much easier to integrate OpenFaaS into the existing infrastructure without changing the existing configurations.

I hope it answers to your questions. These all were a reason this PR were created to address the real issue I hit during evaluating OpenFaaS on Nomad.

**Comment by acornies** [comment]
@hxalid Can handle this internal requirement another way? As in, at a prometheus level, use a custom metrics endpoint that you can't get around, then you create a reverse proxy or some other tcp interceptor to forward requests to http(s)://gateway:{port}/metrics in your nomad cluster? This would satisfy both requirements, without optionally changing the signature on the gateway component itself.
I know this is a workaround, but it sounds like workarounds need to be done anyway if strict rules against default metrics endpoints are being enforced in your organization anyway.

**Comment by hxalid** [comment]
@acornies Sure. It is definitely possible to come up with a workaround or build OpenFaaS from source with the required changes. I thought this change would not break anything, as the default value of the endpoint is still /metrics anyway. It should not break anything unless someone explicitly overrides it. Moreover, OpenFaaS already provides over 10 environmental overrides, adding one more override would not break the convention over configuration approach of OpenFaaS. It is something nice to have but is definitely not a blocking thing. I already used a custom built with these changes for my evaluations.

**Comment by acornies** [comment]
I see no functional problems with the change, and if this helps you evaluate OF then that's great! Thanks for opening the PR.

The broader question is support for non-default values of this new option and what implications it has on other projects in the ecosystem. I'm unsure at this point, but I'd lean on @alexellis and other core contributors.

**Comment by yurilaaziz** [comment]
thank you @hxalid, I have the same issue as you. changing /metrics by /health variant (🤣 ). 
even it's bad to not respect standards, I think is better to let users change  the configuration default values. the PR doesn't harm the general behavior. 
LGTM

**Comment by alexellis** [comment]
What is the problem with the health endpoint? This is rarely ever configurable and has knock-on impact.

**Comment by yurilaaziz** [comment]
@alexellis could you explain your point of view of not merging his PR ? 
Even if users raises new issues because they just missed up with the default value of metrics. 
if it needs more refactoring and design we could help. 

Answer to your question about the problem with the health endpoint: there is no problem :p

**Comment by alexellis** [comment]
Hi @hxalid,

Thanks for your detailed blog post.

Did you decide to use OF + Nomad at Jet?

Alex

**Comment by hxalid** [comment]
Hi @alexellis,

Thank you for your feedback on the blog post! 

We decided to wait until the evaluated serverless runtimes provide more IO abstractions and workflow engines. It would probably make sense for us to evaluate serverless runtimes again in near future as serverless technologies evolve quite fast.

It would be great to see a workflow engine and an improved Kafka controller in OpenFaaS. I know you have an open issue (https://github.com/openfaas/faas/issues/470) to address some of these challenges. In terms of Kafka controller, adding batching, retrying, and  potentially being able to use Confluent's Apache Kafka Golang client as an underlying Kafka library for a better performance would be nice improvements.

**Comment by alexellis** [comment]
Great to hear it.

I'll close this PR now, but it would be great if you would like to contribute into the areas you mentioned above.

Thanks to everyone else who commented on this thread, your PRs are more than welcome - please join Slack and we'll help you get started. https://docs.openfaas.com/community. 

Alex

**Comment by alexellis** [comment]
Derek lock

**Pull request closed without merging**
