### PR TITLE
Updated industry mentions to include DevNet Sandbox

### PR DESCRIPTION
**Pull request by TomDaviesUK**
Signed-off-by: TomDaviesUK <thodavie@cisco.com>

## Description
Updated the industry mentions table to include the new OpenFaaS DevNet Sandbox.

## Motivation and Context
- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?
Documentation change only.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation Update

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by TomDaviesUK** [comment]
@alexellis - Yeah - I know what you mean. You might even consider a new table of 'OpenFaaS Test / Development Environments' or similar. I didn't want to seem to pushy with the first pull to this repo :)

**Comment by rgee0** [comment]
@TomDaviesUK I'd like to see this being introduced/demo-ed at the upcoming community call on Tue 14 Aug 2018 16:00 – 17:00 BST.  Would that be possible?

Awards/mentions probably isn't the right place.  I think we can take a view on the most appropriate placement following the demo.

**Comment by alexellis** [comment]
Tom I've sent an invitation, let us know if you could demo the environment there and how it works?

**Comment by alexellis** [comment]
@ivanayov please can you close this PR and raise a new one where you add the link to the blogs section?

**Comment by ivanayov** [comment]
Derek close

**Pull request closed without merging**
