### PR TITLE
Migrate packages to openfaas org

### PR DESCRIPTION
**Pull request by johnmccabe**
## Description

This PR migrates those packages which have moved from the `github.com/alexellis/faas` repo to the `github.com/openfaas/faas` org.

## Motivation and Context

- [x] I have raised an issue to propose this change (#123)

## How Has This Been Tested?

Testing in progress:
- [x] Build successfully completes
- [ ] Function using newly built watchdog works without error
- [x] Gateway service built from migrated packages works without error

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/alexellis/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
> NOTE not all github.com/alexellis/ repos have moved.

Which remain?

**Comment by johnmccabe** [comment]
@alexellis no, none block the move, the ones remaining were for projects that are still personal, derek, dockercon etc.

**Comment by alexellis** [comment]
Hey @johnmccabe we've got a minor merge conflict here now. Can you jump in when you have 15 min to resolve and I'll merge?

**Comment by alexellis** [comment]
@johnmccabe this needs looking at when you have 5 👍

**Comment by johnmccabe** [comment]
@alexellis that should be good to go now, have tested a stack deploy and with a function built using a new watchdog

**Comment by alexellis** [comment]
LGTM

**Pull request merged**
