### PR TITLE
Update faas-provider to 0.16.2

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

This provider version adds secrets/envVars to the list funcions endpoint
if they are provided by the provider.

Signed-off-by: Alistair Hey <alistair@heyal.co.uk>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label
Part of work to add secrets/env vars to faasd/faas-netes 

## How Has This Been Tested?

built locally and deployed for faasd, 

```sh 
untu# curl http://admin:$OFPWD@localhost:8080/system/functions | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   397  100   397    0     0  12406      0 --:--:-- --:--:-- --:--:-- 12406
[
  {
    "name": "bar",
    "image": "docker.io/library/alpine:latest",
    "namespace": "openfaas-fn",
    "secrets": [
      "bar"
    ],
    "labels": {},
    "annotations": {}
  },
  {
    "name": "figlet",
    "image": "docker.io/functions/figlet:0.13.0",
    "namespace": "openfaas-fn",
    "labels": {},
    "annotations": {},
    "replicas": 1
  },
  {
    "name": "foo",
    "image": "docker.io/library/alpine:latest",
    "namespace": "openfaas-fn",
    "secrets": [
      "goo",
      "foo"
    ],
    "labels": {},
    "annotations": {}
  }
]

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Looks good.

Can you rebase due to #1617?

Alex

**Comment by alexellis** [comment]
Want to re-open?

**Comment by Waterdrips** [comment]
I think the go modueles PR also included this change and thus this is a no-op now!

**Comment by alexellis** [comment]
Thanks for confirming. I'll cut a build

**Pull request closed without merging**
