### PR TITLE
Added function url field and copy action to the UI

### PR DESCRIPTION
**Pull request by kenfdev**
Signed-off-by: Ken Fukuyama <kenfdev@gmail.com>

## Description

This change adds a function URL field to the UI and a 'copy to clipboard' button next to it. If the browser does not support the copy command, the copy icon will be hidden.

clipboard_feature

The following is how it looks like when the browser doesn't support clipboard copy.

ss 2018-07-13 23 23 31

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

https://github.com/openfaas/faas/issues/765

## How Has This Been Tested?

1. Click a function
2. Click the copy icon next to the URL field
3. Check if the URL was copied by pasting it somewhere

Tested browsers
- [x] Chrome 67.0.3396.99
- [x] Firefox 60.0.1
- [x] Safari 11.1.2 (12605.3.8.1)
- [ ] IE11
- [ ] Edge

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by kenfdev** [comment]
You can test this UI with `kenfdev/gateway:latest-dev` this image.

Would be of great help if somebody could test this with IE11 and Edge.

**Comment by kenfdev** [comment]
@burtonr Please, could you test this on a windows environment? I greatly appreciate it!

**Comment by alexellis** [comment]
Derek set milestone: 0.8.6

**Comment by kenfdev** [comment]
@burtonr Thanks a lot Burton for testing this PR!

**Pull request merged**
