### PR TITLE
new blog post added to Blog posts in 2020 section

### PR DESCRIPTION
**Pull request by developer-guy**
another great post published about getting started openfaas by appfleet team then i added it to community guides.

### CODE REVIEW

**Comment by alexellis** [comment]
Sorry this needs a rebase. How about you send a new PR from a new branch so that the conflicts are gone?

Alternative run `git rebase -I HEAD~2` and then do a force push.

**Comment by developer-guy** [comment]
> Sorry this needs a rebase. How about you send a new PR from a new branch so that the conflicts are gone?
> 
> 
> 
> Alternative run `git rebase -I HEAD~2` and then do a force push.

I already resolved conflicts , done ✅

**Comment by alexellis** [comment]
Hi you still need to squash your three commits. We explain how to do this in the contribution guide.

Failing that raise a new PR.

Alex

**Comment by alexellis** [comment]
Fixed via #1531 - thank you

**Pull request closed without merging**
