### PR TITLE
added graphql blog post

### PR DESCRIPTION
**Pull request by kenfdev**
Added a GraphQL Blog Post Entry.

### CODE REVIEW

**Comment by johnmccabe** [comment]
Looks good to me 👍 , nice post @kenfdev

**Comment by alexellis** [comment]
LGTM too. @JockDaRock could this integrate with the Flask work somehow?

**Comment by alexellis** [comment]
Have you posted it on Hacker News or similar sites @kenfdev ?

**Comment by kenfdev** [comment]
@alexellis No I haven't. Unfortunately I'm not familiar with those sites. Do I just submit it in HN?? Sorry for the noob question.

**Comment by alexellis** [comment]
Yes - you may need to do it several times. Sign up then head over to: https://news.ycombinator.com/submit

Prefix the title with "Show HN" - but don't share the direct link to the post afterwards.

**Pull request merged**
