### PR TITLE
Adding TestDrive information about the store

### PR DESCRIPTION
**Pull request by jmkhael**
Signed-off-by: Johnny Mkhael <johnny.mkhael@gmail.com>

Adding TestDrive information about the store to show new functionality

## Motivation and Context
Have the documentation covering new functionality

## How Has This Been Tested?
README.md and TestDrive.md changed

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by jmkhael** [comment]
Derek add label: documentation

**Comment by alexellis** [comment]
Derek add label: documentation

**Comment by alexellis** [comment]
Hey @jmkhael if it's not too much trouble please revert the README (since it's too long already) and add some padding or a header around the store 👍 Then good to merge.

**Comment by alexellis** [comment]
Feel free to re-open the PR when you've made the changes.

**Pull request closed without merging**
