### PR TITLE
Adds env-vars to store

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Adds env-vars to store

## Motivation and Context

Needed for the inception function so that it doesn't time-out due to the defaults for the function.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@kenfdev please can you take a look at this change?

**Comment by ericstoekl** [comment]
I just tested this by pulling the changes, and it works. 👍

**Comment by alexellis** [comment]
You star! Merged

**Comment by kenfdev** [comment]
Thanks @ericstoekl ! And the code LGTM 👍

**Pull request merged**
