### PR TITLE
Bump gorilla mux to 1.6.2

### PR DESCRIPTION
**Pull request by LucasRoesler**
## Description

- Update  and vendor gorilla 1.6.2

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

See #945 

## How Has This Been Tested?

Testing is in progress, I will test it manually by building a new gateway and then validating that the UI behaves as expected.  Similarly, I will deploy, invoke, and then remove a function using the CLI

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
The integration tests as part of CI appear to be working, let me know when the PR is ready for merge.

**Comment by LucasRoesler** [comment]
I just tested this again today, and everything looked good (UI was working and I deployed a function via the CLI)

**Comment by alexellis** [comment]
Thanks for updating. Do any other projects need this change?

**Comment by alexellis** [comment]
Derek set milestone: 0.9.12

**Comment by LucasRoesler** [comment]
@alexellis i checked through each of the providers and a few other projects that might use the mux, only faas-netes was behind, on v1.6.1 https://github.com/openfaas/faas-netes/blob/4cad8c225ef6ee2172e5f722d6708d8130eccec6/Gopkg.lock#L120

There isn't a lot of rush to upgrade, but I will create a ticket to bump it there too

**Comment by alexellis** [comment]
:+1: is it upgraded by upgrading the faas-provider version?

**Comment by LucasRoesler** [comment]
It is directly imported in two spots, but I do think that upgrading the provider will cause gorilla to also upgrade

**Comment by LucasRoesler** [comment]
Sorry I just checked, there is actually a constraint for the mux in the Gopkg.toml

**Pull request merged**
