### PR TITLE
Add 3 KubeCon video links to community file

### PR DESCRIPTION
**Pull request by burtonr**
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

## Description

Add video links to Kubecon talks in the community file

Some of the talks were already present with a link to the event, so I've just added an additional link to the existing row for the video so as not to lose the event information.

If you'd rather have duplicated records, one for the event, and one for the video, I'm happy to refactor this change. Perhaps the video link could go into the "writeups" section with some of the other videos.

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [X] My issue has received approval from the maintainers or lead with the `design/approved` label
Spoke with Alex via Slack

## How Has This Been Tested?

Verified the links were functional and previewed the markdown rendering with VSCode

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Can these go into a featured video section instead please?

**Comment by alexellis** [comment]
@burtonr please see my comment.

**Comment by alexellis** [comment]
@burtonr

**Comment by burtonr** [comment]
@alexellis I've added the featured videos section. I chose not to remove the same record from the events list as I feel it belongs in both places. If someone is looking for a talk from a certain date, they may not know to look for it in the "Featured Videos" section, likewise, someone looking for a video may not know to look in the events section.

**Comment by alexellis** [comment]
I can only see the featured videos section (added), which is what I was hoping to see.

**Pull request merged**
