### PR TITLE
Add link to www.openfaas.com on OpenFaaS Icon.

### PR DESCRIPTION
**Pull request by thom8**
## Description

Link the icon in the OpenFaaS portal to www.openfaas.com.

### CODE REVIEW

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by alexellis** [comment]
@thom8

**Comment by alexellis** [comment]
@jmkhael ?

**Comment by jmkhael** [comment]
Review LGTM. 
How do you propose to test this? is there a deployment for this somewhere?

**Comment by alexellis** [comment]
To test UI changes .. https://github.com/openfaas/faas/blob/master/contrib/HACK.md

**Comment by jmkhael** [comment]
my bad. I don't know why I though we are talking about openfaas.com website for a while...

**Comment by thom8** [comment]
Hey @alexellis, just in transit from and conference in San Fran and heading back to Melbourne, planned to jump on this once I got home. So thanks for sorting this out.

Looking forward to getting more involved and I think you've got a few more fans after the conference last week ;)

**Pull request merged**
