### PR TITLE
Updated armhf images in docker-compose.armhf.yml

### PR DESCRIPTION
**Pull request by zeerorg**
Signed-off-by: Rishabh Gupta<r.g.gupta@outlook.com>

## Description
Updating docker images for armhf OpenFaas deployment to latest versions.

## Motivation and Context
This change updates the docker images to latest versions.
- openfaas/gateway:0.9.10-armhf -> openfaas/gateway:0.9.14-armhf
- openfaas/faas-swarm:0.5.0-armhf -> openfaas/faas-swarm:0.6.1-armhf
- openfaas/queue-worker:0.5.3-armhf -> openfaas/queue-worker:0.5.7-armhf

## How Has This Been Tested?
1. Update the images in docker-compose.armhf.yml
2. run `docker stack deploy func -c ./docker-compose.armhf.yml`
3. Openfaas Gateway should be available at port 8080
4. The function invocations are reset, so try to invoke functions and see the count going up

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Glad you worked out the DCO.

Thank you for this PR!

**Comment by alexellis** [comment]
Please could you update for armhf on faas-netes next? We use a series of YAML files there.

If you can't test then please reach out in thy community Slack for a helper.

**Comment by zeerorg** [comment]
Should I create an issue in faas-netes, this way someone can create a quick pr?

**Comment by alexellis** [comment]
Please do 👍

**Comment by alexellis** [comment]
(You don't have to ask)

**Pull request merged**
