### PR TITLE
Update for ARM builds

### PR DESCRIPTION
**Pull request by miketide420**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by rgee0** [comment]
Reference #321

**Comment by alexellis** [comment]
Looks good @miketide420 do you want to re-test and resolve the git conflict?

**Comment by alexellis** [comment]
@miketide420 @rgee0 please could you test so I can merge or close?

**Comment by alexellis** [comment]
Closing due to lack of activity.

**Comment by alexellis** [comment]
Derek add label: revisit

**Pull request closed without merging**
