### PR TITLE
Fix Padding on UI and remove Namespace when not needed

### LINKED ISSUE #1450: Padding broken in the UI for the store pop-up
## Description 

The padding is broken in the UI for the store pop-up. It would be good to have this more balanced, see the below example:

75097546-d92f3000-55a3-11ea-9780-1bbe80a57370

### LINKED ISSUE #1452: Namespace added onto gateway function url when single namespace enabled
the Gateway UI is appending the namespace to the function URL when we are running on faas-netes but only have a default namespace, we dont need to add this and it may cause issues with scaling 

## Expected Behaviour

only have ns suffix on 

## Current Behaviour

We always get a ns on faas-netes

### PR DESCRIPTION
**Pull request by Waterdrips**
Fixes #1450
Fixes #1452

## Description
There was a no-padding class set on all of the headers, but the funcstore needed
the padding, It's been fixed.

There was also a case when using faas-netes where a single-namespace deployment was appending the namespace
to the function url, this isn't needed as the default namespace is used when no specific one is provided.

I have also added a new env var to make in the gateway directory so I can more easily build and push to my own dockerhub
repo. Building for OpenFaaS has not changed.

I have also fixed an issue in the deploy_stack.sh script where newlines (\n) were not being printed as newlines and the 
literal chars were printed instead. This makes getting the password a lot easier for swarm users.

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [x] My issue has received approval from the maintainers or lead with the `design/approved` label

## How Has This Been Tested?

Faas-Swarm, Faas-Netes tested.

UI deployed on swarm, no fn-namespace suffix, and padding is included on funcstore.

On Faas-Netes:
Single NS deployment: 
- padding present
- no ns suffix on function url now

Multi-NS deployment:
- padding present
- suffixes present on all namespaces

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you for your patch

Please can you edit the commit messages?

Title: 50-70 chars
Body: 72 chars

**Comment by alexellis** [comment]
Can you add an after screenshot

**Comment by Waterdrips** [comment]
> Can you add an after screenshot please?

Screenshot from 2020-02-24 07-37-12

**Comment by Waterdrips** [comment]
@alexellis can we get this merged?

**Comment by alexellis** [comment]
Can we get a screenshot with the current version please?

**Comment by Waterdrips** [comment]
image

image

**Comment by alexellis** [comment]
Screenshot 2020-03-01 at 15 58 02

Whilst editing, could you tighten up the padding between each row?

**Comment by Waterdrips** [comment]
> Whilst editing, could you tighten up the padding between each row?


If only it were that easy :sweat: 
I can have a go

**Comment by alexellis** [comment]
What's the challenge? Can you link me to the code?

**Comment by Waterdrips** [comment]
its all based on the default css settings from angular-bootstrap, we could add overrides but it would need to be on 4 or 5 different elements and could cause issues elsewhere. 

Its this repeating section here: https://github.com/openfaas/faas/blob/master/gateway/assets/templates/funcstore.html#L14

The heights are set by angular-bootstrap defaults on most of the elements in that repeating group, 
Iv tried the suggestions here: https://github.com/angular/material/issues/7346 and https://github.com/angular/material/issues/7277

**Comment by alexellis** [comment]
Thank you for explaining, that helps a lot. Let's merge what we have today.

**Pull request merged**
