### PR TITLE
Added OpenFaaS Bangalore Meetup Event

### PR DESCRIPTION
**Pull request by tarunmangukiya**
## Checklist:

- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`

### CODE REVIEW

**Comment by viveksyngh** [comment]
@tarunmangukiya 

Please sign off your commits with `git commit -s`.
Also, It is recommended not to delete anything from PR template.

**Comment by viveksyngh** [comment]
Derek add label: duplicate

**Comment by viveksyngh** [comment]
Derek add label: duplicate

**Comment by viveksyngh** [comment]
@tarunmangukiya I am closing this issue as it is duplicate.

**Comment by viveksyngh** [comment]
Derek close

**Comment by alexellis** [comment]
👍 we have this via @viveksyngh

**Pull request closed without merging**
