### PR TITLE
[blocked] Remove sample functions for swarm

### PR DESCRIPTION
**Pull request by ericstoekl**
Signed-off-by: Eric Stoekl <ems5311@gmail.com>

## Description

Remove the sample function from the `docker-compose.yml` file. This removes these functions for the Docker Swarm deployment.

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
https://github.com/openfaas/faas-cli/issues/415

## How Has This Been Tested?

```
$ ./deploy_stack.sh 
Deploying stack
Creating network func_functions
Creating config func_prometheus_config
Creating config func_prometheus_rules
Creating config func_alertmanager_config
Creating service func_queue-worker
Creating service func_prometheus
Creating service func_alertmanager
Creating service func_gateway
Creating service func_faas-swarm
Creating service func_nats
```

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@ericstoekl this PR does not address the wider concerns of the existing user base and documentation. This is explained in the issue, so please could you refer back to the discussion there? For now I'll mark this PR as blocked.

You need to update everywhere that references and mentions these sample functions including:
* The TestDrive (Markdown + docs.openfaas.com)
* docs.openfaas.com
* Suggest which blogs need editing that use the samples

Create a new YAML file to represent the missing functions (ideally in a stack.yml format if possible)

We're making effectively a breaking change so let's make it easy for users to get back to the samples they've been used to if they want them back.

**Comment by ericstoekl** [comment]
Thanks for the feedback @alexellis. Updated this PR to include a `stack.yml` and `stack_arm.yml` for the arm functions. Updated the `TestDrive.md` to include instructions on how to deploy the starter functions.

I will submit a separate PR to the docs repo for the rest of the work.

**Comment by alexellis** [comment]
Thanks - can you find someone to test this and verify the changes? @rgee0 or @kenfdev perhaps? If you guys can test over the weekend I could merge on Sunday.

**Comment by BurtonR** [comment]
@ericstoekl This is great! Cloned this PR and ran `./deploy-stack.sh` (on Ubuntu 18.04) and works as expected. Only the core services were deployed.

Also ran `faas deploy` to deploy the sample functions and verified everything is deployed and functional
:100:

**Comment by alexellis** [comment]
Thanks Burton.. that's merged. Let's see how this goes :)

**Comment by alexellis** [comment]
Derek set title: Remove sample functions from default deployment on Docker Swarm

**Pull request merged**
