### PR TITLE
Added Belo Horizonte Meetup

### PR DESCRIPTION
**Pull request by zeerorg**
Signed-off-by: Rishabh Gupta <r.g.gupta@outlook.com>

## Description
Added Belo Horizonte Meetup organized by @pasimoes to community file.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you

**Comment by pasimoes** [comment]
Hi Alex and Rishabh could you please modify this event? I change the idea and now we are have a serie "Serverless Functions Frameworks" and 1st ep will be OpenFaaS .. 
So, the name of event is "Serverless Functions Frameworks : OpenFaaS Day"

The speakers are : 
@marceloumberto presenting a overview of @openfaas
@jeffotoni comparing @openfaas with lambda

Thank you so much!

**Comment by zeerorg** [comment]
@alexellis @pasimoes can you atke a look at #1239 to seeif that's okay ?

**Comment by alexellis** [comment]
No problem

**Pull request merged**
