### PR TITLE
Fix for faas-invoke - flag should be '-g' or '--gateway'

### PR DESCRIPTION
**Pull request by herochinese**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by herochinese** [comment]
Signed-off-by: Joe Smith <joe.smith@email.com>

**Comment by johnmccabe** [comment]
@herochinese you need to sign your commit.
```
git commit --amend -s
```
Then `--force` push your `patch-1` branch again.

**Comment by alexellis** [comment]
LGTM - but please make the change mentioned by @johnmccabe before we can merge.

Alternatively - raise a new PR via the UI and add the text to the end:

```

Signed-off-by: Your Name <you@domain.com>
```

**Comment by alexellis** [comment]
Derek set title: Fix for faas-invoke - flag should be '-g' or '--gateway'

**Comment by herochinese** [comment]
It's tiny thing.  Just floating here, and try to find something to do.

**Comment by alexellis** [comment]
Hey @herochinese - I'd obviously prefer to take the contribution from you, but we do have a contribution guide that needs to be followed. Are you able to sign-off the commit with your real email address or should we pick this up ourselves? Please let me know by the end of the day.

**Pull request merged**
