### PR TITLE
Added Openfaas September Event happening at Bangalore

### PR DESCRIPTION
**Pull request by saiyam1814**
Signed-off-by: Saiyam Pathak <saiyam911@gmail.com>

Description
Added all the talks from the September Openfaas Event Happening at Microsoft Office, Bangalore, India

How Has This Been Tested?
Changed only the community file

Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
This looks good but could you do it as one meet-up event please?

**Comment by saiyam1814** [comment]
Ok will do and in the authors section add all 4 names , that should be fine ?

**Comment by alexellis** [comment]
I would just put the name of the meet-up group.

**Comment by saiyam1814** [comment]
@alexellis  Is it fine now ?

**Pull request merged**
