### PR TITLE
fix sample-functions/Nmap

### PR DESCRIPTION
**Pull request by chennqqi**
fix two package dependency problems:

1. could not locate nse_main.lua
2. could not locate scripts directory

## Description

add nmap runtime script lib `nmap-scripts` package of alpine

## Motivation and Context

fix error message:

NSE: failed to initialize the script engine:
could not locate nse_main.lua

## How Has This Been Tested?

after `apk add --no-cache  nmap-scripts` 
this function run sucessfully and dosen't show error message above anymore

## Steps to Reproduce (for bugs)
1.  Deployed nmap via UI
2.  Enter `-A www.baidu.com`  or some other real site/ip  `-A 10.0.0.1`
3.  nmap will show message
image
4. enter into docker
5. run `apk add --no-cache nmap-scripts`
7. redo step 1 you will see `nmap -A` run sucessfully

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alexellis** [comment]
Hi @chennqqi,

Thank you for your contribution.

I am not sure if English is your first language, but I wanted to let you know that we will need a few things to consider merging this:

1) Don't answer "yes" to "How has this been tested?" Instead, give specific details of what issue was present and how it was fixed, then how it was verified (proven to be fixed)
2) Please fill out the whole template
3) Log details of what you believe to be wrong or missing with the function in a new issue in the openfaas/faas repo

Finally, please sign off the commit.

Thanks again

Alex

**Comment by chennqqi** [comment]
--signoff already appended

**Comment by rgee0** [comment]
Each commit needs sign-off so I think the merge commit is causing the `no-dco`.  Try squashing the commits?

**Comment by alexellis** [comment]
Thanks @rgee0 

@chennqqi unfortunately I cannot reproduce the issue and you didn't include any instructions for reproducing the issue.

```

## Steps to Reproduce (for bugs)
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1.
2.
3.
4.

```

^ You deleted this instead of filling it out, please could you give the instructions required to reproduce the error?

This is what I did:

* Deployed nmap via UI
* Entered `-sP 192.168.0.0/24`
* Observed the hosts found on my local network

Everything worked :heavy_check_mark: 

Alex

**Pull request closed without merging**
