### PR TITLE
Added new entry in community.md - blogs section - for Functions as a Service with openFaas

### PR DESCRIPTION
**Pull request by mfarache**
Signed-off-by: Mauricio Farache <mauricio.farache@piksel.com>

## Description

Added new entry in the blogs sections with a reference to my recent blog post on my personal blog about openFaas with Kubernetes. I tried to explore as many items as possible. Everything worked like a charm.

## Motivation and Context

Sharing knowledge

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

No test nor changes to the code
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
No changes to code
## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ X] I have updated the documentation accordingly.
- [ X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Hi thank you for your interesting blog. I think you should really remove the section claiming that auto-scaling doesn't work. It clearly works but needs enough traffic to warrant it kicking in. For one you had a sleep in there...

You simply are not generating enough traffic and the blog will be misleading to other people who don't know the project.  Click the Alerts page in Prometheus and make sure you're actually triggering the high traffic alert.

**Comment by mfarache** [comment]
ok, I will try again without the sleep but I think I already tested that way and then everything got not responsive. Could it be that works for Swarm and not for K8?  
I will retest everything and let u know when the new post is ready

**Comment by mfarache** [comment]
you were right, I was not generating enough traffic as I could inspect that none of the Alerts where active. I have amended the blog post, let me know if something else needs to be modified. I want to spread the word and share with co-workers so what better than having your feedback ;)

**Comment by alexellis** [comment]
I do like the post overall and I think it's positive. I've noticed 1-2 dozen typos. I think you should run through a spell-check in word or similar before we share your blog.

* OpenFaaS needs to be cased correctly as OpenFaaS
* funker is not an alternative (I wouldn't mention it)
* Fision is spelt Fission

* wiht -> with

It's also worth linking to here and adding a couple of screenshots (maybe of the store?)

In this blog - under Build/ship/run we have some key advantages over other frameworks including the fact that a Docker image format is used for an immutable function. https://medium.com/devopslinks/getting-started-with-openfaas-on-minikube-634502c7acdf

I've invited you to the community. Looking forward to seeing you there.

**Comment by mfarache** [comment]
great, appreciate your feedback! 

non a native english speaker so bear with me, hopefully typos are gone now. 

About the screenshots.. there was already an image of the Store on the Open FaaSsection".
I added links as suggested and image about the announcement itself you made a week ago.

Also I have added how the Graphane panel looks like

Thanks!

**Comment by alexellis** [comment]
Thanks. There was one more typo "bee" should be "been" I guess 👍

**Pull request merged**
