### PR TITLE
Publish to multiple topics

### PR DESCRIPTION
**Pull request by alexellis**
## Description

Publish to multiple topics

Enables publishing to various topics according to annotations
on the functions. The function cache is moved up one level so
that it can be shared between the scale from zero code and the
queue proxy.

## Motivation and Context

Covers the publishing portion of: #1330 

## How Has This Been Tested?

Unit testing added for parsing namespaces, more to follow with
e2e testing.

```bash
arkade install openfaas --clusterrole \
 --set gateway.image=openfaas/gateway:0.18.16-rc5 \
 --set queueWorker.image=openfaas/queue-worker:0.10.1

kubectl create ns dev
kubectl annotate ns/dev openfaas=1
```

Then:

```bash
faas-cli store deploy nodeinfo
faas-cli store deploy figlet -n dev --annotation com.openfaas.queue=slow-queue
```

Then add a queue-worker by exporting the existing one and altering its name, then run kubectl apply.

```
kubectl get -n openfaas queue-worker -o yaml > slow-worker.yaml
```

Or apply this gist:

```

# Review the changes: 
cat https://gist.githubusercontent.com/alexellis/b240e9d7758086c33af7f7aa063850ab/raw/73da966d7bded40dd57e850a16853525605214a8/slow-queue-worker.yaml | less

# Then apply:

kubectl apply -f https://gist.githubusercontent.com/alexellis/b240e9d7758086c33af7f7aa063850ab/raw/73da966d7bded40dd57e850a16853525605214a8/slow-queue-worker.yaml
```

Now invoke the fast queue:

```
curl 127.0.0.1:8080/async-function/nodeinfo -d test
```

Now invoke the slow-queue:

```
curl 127.0.0.1:8080/async-function/figlet.dev -d test
```

Check both messages are processed: 

```
kubectl logs -n openfaas deploy/queue-worker
kubectl logs -n openfaas deploy/slow-queue-worker

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alexellis** [comment]
Here is a video demo of me running through the smoke test: https://youtu.be/VdggUjexbuI

**Comment by alexellis** [comment]
CI passes
E2e test pass
Smoke test passed with new behaviour and scale from zero.

**Comment by alexellis** [comment]
Please help test with the new docs instructions:

https://docs.openfaas.com/reference/async/

**Comment by Amalkh5** [comment]
i did the test on Kubernetes running on minkube :

- minkube version `minikube v1.9.0 on Darwin 10.15.3`
- Kubernetes `version v1.18.0`
-  kubectl `version v1.18.0`
- faas-cli  `version 0.12.2`

## Test Steps:
1. deploy a new version of faas
```
$ arkade install openfaas --clusterrole  \
--set gateway.image=openfaas/gateway:0.18.16-rc5 \
--set queueWorker.image=openfaas/queue-worker:0.10.1
```
2. deploy test functions 
```
$ faas-cli store deploy nodeinfo

WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://192.168.99.100:31112/function/nodeinfo

$ faas-cli store deploy figlet --annotation com.openfaas.queue=slow-queue
WARNING! Communication is not secure, please consider using HTTPS. Letsencrypt.org offers free SSL/TLS certificates.

Deployed. 202 Accepted.
URL: http://192.168.99.100:31112/function/figlet
```
3.   Create a slow queue-worker 
after creating the file i did update the faas_nats_channel environment variable  value in slow-queue-queue-worker.yaml to `slow-queue1

```

$ export CORE_NS=openfaas

$ kubectl get -n $CORE_NS deploy/queue-worker -o yaml --export > slow-queue-queue-worker.yaml
Flag --export has been deprecated, This flag is deprecated and will be removed in future.
$ sed -ie s/app:\ queue-worker/app:\ slow-queue-worker/g slow-queue-queue-worker.yaml

$ sed -ie s/name:\ queue-worker/name:\ slow-queue-worker/g slow-queue-queue-worker.yaml

$ kubectl create -f slow-queue-queue-worker.yaml --namespace $CORE_NS

deployment.apps/slow-queue-worker created
```

4.  test queue
```
$ curl http://192.168.99.100:31112/async-function/figlet -d "slow queue"
$ kubectl logs  --follow -n openfaas pods/slow-queue-worker-77bd57575-xdf6n
Loading basic authentication credentials
Connect: nats://nats.openfaas.svc.cluster.local:4222
Subscribing to: slow-queue at nats://nats.openfaas.svc.cluster.local:4222
Wait for  1m0s
Listening on [slow-queue], clientID=[faas-worker-slow-queue-worker-77bd57575-xdf6n], qgroup=[faas] durable=[]
[#1] Received on [slow-queue]: 'sequence:1 subject:"slow-queue" data:"{\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"10\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.1\"],\"X-Call-Id\":[\"d888c3c0-bfbf-4c44-a613-da920cefe3d8\"],\"X-Start-Time\":[\"1587580925959653258\"]},\"Host\":\"192.168.99.100:31112\",\"Body\":\"c2xvdyBxdWV1ZQ==\",\"Method\":\"POST\",\"Path\":\"\",\"QueryString\":\"\",\"Function\":\"figlet\",\"QueueName\":\"slow-queue\",\"CallbackUrl\":null}" timestamp:1587580925975495683 '
Invoking: figlet with 10 bytes, via: http://gateway.openfaas.svc.cluster.local:8080/function/figlet/
Invoked: figlet [200] in 0.022471s
figlet returned 312 bytes

$ curl http://192.168.99.100:31112/async-function/nodeinfo -d "fast queue"

$ kubectl logs  --follow --tail 5 -n openfaas pods/queue-worker-6b9d4767df-pbgng
figlet returned 312 bytes
[#5] Received on [faas-request]: 'sequence:5 subject:"faas-request" data:"{\"Header\":{\"Accept\":[\"*/*\"],\"Content-Length\":[\"10\"],\"Content-Type\":[\"application/x-www-form-urlencoded\"],\"User-Agent\":[\"curl/7.64.1\"],\"X-Call-Id\":[\"91d23408-0a59-441d-9abd-3315ab1fb239\"],\"X-Start-Time\":[\"1587580939143498527\"]},\"Host\":\"192.168.99.100:31112\",\"Body\":\"ZmFzdCBxdWV1ZQ==\",\"Method\":\"POST\",\"Path\":\"\",\"QueryString\":\"\",\"Function\":\"nodeinfo\",\"QueueName\":\"\",\"CallbackUrl\":null}" timestamp:1587580939146947711 '
Invoking: nodeinfo with 10 bytes, via: http://gateway.openfaas.svc.cluster.local:8080/function/nodeinfo/
Invoked: nodeinfo [200] in 0.024737s
nodeinfo returned 102 bytes
```

**Comment by alexellis** [comment]
Thank you @Amalkh5 this feedback confirms that things are working as expected and is much appreciated

**Comment by alexellis** [comment]
For anyone landing here, you can now test with the updated docs here: https://docs.openfaas.com/reference/async/#multiple-queues

**Pull request merged**
