### PR TITLE
Update main.go

### PR DESCRIPTION
**Pull request by Dhruval97**
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Dhruval97** [comment]
Removed unwanted lines for Demo

**Comment by johnmccabe** [comment]
Its a spam PR to try and game the Hacktoberfest offer.

**Comment by johnmccabe** [comment]
Derek add label: invalid

**Comment by Dhruval97** [comment]
I am creating a video series on how to use Git and GitHub . For that I randomly pick one and applied . @johnmccabe I am not a spammer .

**Comment by johnmccabe** [comment]
Ok, we specifically ask that people raise issues before raising PRs in the CONTRIBUTING.md, that you'd not done so and with a change containing only newline updates which was immediately closed by yourself it looked very suspicious.

Better if you perhaps use a repo you control for demo purposes when insta-closing, or at least let the repo maintainers know in advance if you're intending to open/close PRs for the purposes of recording a video.

**Comment by alexellis** [comment]
Closing as invalid. Thanks for commenting @johnmccabe

**Pull request closed without merging**
