### PR TITLE
Add article in community file

### PR DESCRIPTION
**Pull request by martindekov**
Adding article with original french title
from lemagit to the list of articles written
on the topic

Signed-off-by: Martin Dekov (VMware) <mdekov@vmware.com>

Added french article `Serverless: quelle approche retenir` by Twain Taylor to the community files mentioning articles on the topic

## Description

See description above ^

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

Requested

## How Has This Been Tested?

N.A.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Docs/MD file update 

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
I was thinking of adding this to the general 2019 blog posts entry/list? Wdyt?

**Comment by burtonr** [comment]
I agree with Alex. This article is nice, but not an award. It should be in the section labeled "Blog posts and write-ups 2019"

you could almost call this line an award though :smile: 
> OpenFaaS est le framework open source serverless le plus populaire.

Translated (via Google Translate):
> OpenFaaS is the most popular open source serverless framework.

**Comment by martindekov** [comment]
😄 OMG you are right ... I did it kinda late and placed in the wrong table my mistake ... I will amend soon

**Comment by alexellis** [comment]
I've added your text from the PR in another commit. Thanks.

**Pull request closed without merging**
