### PR TITLE
serverless memes function post link

### PR DESCRIPTION
**Pull request by mlabouardy**
Signed-off-by: mlabouardy <mohamed@labouardy.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you @mlabouardy - you just need to put the submission in date order like the other blog posts.

Note - rather than forking the "openfaas/faas" repo - I'd suggest you just put together a new repo with the contents of the "Memes9Gag" folder.

**Comment by mlabouardy** [comment]
@alexellis  done + code repo: https://github.com/mlabouardy/memes-faas

**Comment by alexellis** [comment]
Great. We can merge the link. I am seeing that the image you used is a tiny resolution.. I can't read it. Maybe you can update that and quote the JSON in the blog post?

https://github.com/mlabouardy/memes-faas/blob/master/example.png

Also what are people meant to do with the result? Manually find the URL in a web browser? Maybe you could have the function return the bytes of the first meme?

**Comment by mlabouardy** [comment]
@alexellis fixed

I build a 9Gag Android application which consumes the JSON response of the function: http://www.blog.labouardy.com/create-9gag-android-application/

**Comment by alexellis** [comment]
Merged

**Pull request merged**
