### PR TITLE
Fix fwatchdog timer memory leak issue

### PR DESCRIPTION
**Pull request by mikechiuP**
Use timer.AfterFunc to make sure goroutine could be gc.

Signed-off-by: Mike Chiu <mike.chiu@pentium.network>

Fix fwatchdog leak after stress testing or heavy loading.

## Description

Use time.AfterFunc to replace timer.NewTimer to avoid leak.

## Motivation and Context

- [x] I have raised an issue to propose this change ([#1000](https://github.com/openfaas/faas/issues/1000))

## How Has This Been Tested?

1. use build.sh to build fwatchdog image
2. run docker: ```docker run -it --entrypoint=sh --name=watchdog -p 8080:8080 {image}```
3. set env. variable: ```export fprocess="cat /etc/hostname"```
4. execute fwatchdog http server: ```fwatchdog```
5. outside the container, monitor stats of container: ```docker stats watchdog``` 
6. use ab to do stress testing: ```ab -n 1000 -c 100 https://localhost:8080```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by mikechiuP** [comment]
@alexellis  Thanks ur reply! :-)
According to the [comment](https://github.com/golang/go/issues/20989#issuecomment-315068908)
This because go routine holds timer even if timer be closed, that makes go-routine will never be GC.

**Comment by alexellis** [comment]
Derek set milestone: 0.9.12

**Comment by alexellis** [comment]
There must be a valid use-case for using timers in go routines. What would allow GC to reclaim?

**Comment by alexellis** [comment]
@mikechiuP I am happy with the code change, but I would like to see some end to end testing to show that the cut-off from the timer is still working and valid.

**Comment by alexellis** [comment]
Derek add label: blocked

**Comment by alexellis** [comment]
Blocked until further e2e testing done to prove the positive test-case of timeouts being clipped successfully and giving the same HTTP code as before.

**Comment by burtonr** [comment]
I've run through and tested this a bit. It does appear to still be respecting the timeout, and the results are the same

Using the current latest watchdog:
screenshot from 2018-12-30 18-04-26

Using this updated watchdog:
screenshot from 2018-12-30 18-05-03

It looks like this is a harmless change that will add benefit.

**Comment by alexellis** [comment]
Thank you @mikechiuP 🎉 

Thanks @burtonr for verifying

**Pull request merged**
