### PR TITLE
Update backers

### PR DESCRIPTION
**Pull request by vinodkottem**
To add Vinod K Kottem to BACKERS.md file as a backer

Signed-off-by: vinodkottem <vinodkumarkottem@gmail.com>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))
- [ ] My issue has received approval from the maintainers or lead with the `design/approved` label

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thank you :-)

How are you backing and where?

**Comment by vinodkottem** [comment]
> Thank you :-)
> 
> How are you backing and where?



> Thank you :-)
> 
> How are you backing and where?

Via paypal and transaction ID is (6C027359YX7741326)

**Comment by alexellis** [comment]
Is that on GitHub or Patreon?

**Comment by vinodkottem** [comment]
> Is that on GitHub or Patreon?

GitHub , used this [link](https://paypal.me/openfaas?locale.x=en_GB)

**Comment by alexellis** [comment]
Thank you, that is very kind of you. 

This page is just for regular backers who are using the GitHub or Patreon website to give a sum monthly of 5USD or more. If you like, you could retract your payment and make it through GitHub? 

Thank you again

**Comment by vinodkottem** [comment]
> Thank you, that is very kind of you.
> 
> This page is just for regular backers who are using the GitHub or Patreon website to give a sum monthly of 5USD or more. If you like, you could retract your payment and make it through GitHub?
> 
> Thank you again

Got it. Closing this for now.

**Pull request closed without merging**
