### PR TITLE
Add call-id via middleware

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

## Description

Adds a call-id as a middleware for all calls passing through gateway

## Motivation and Context

To enable debugging and tracing

## How Has This Been Tested?

Via local build with Swarm

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@JockDaRock @kars7e

**Comment by kars7e** [comment]
Would also like to eventually add support for OpenTracing?

**Comment by alexellis** [comment]
Yes we should look into it again.

**Comment by kars7e** [comment]
OpenTracing will come with its own inject mechanism, but one suggestion that I have for this patch is to only set this header to generated uuid if the header is not part of the request or is empty. This way users can inject their own tracking ID in some more complex applications.

**Comment by alexellis** [comment]
OK, if it exists already it won't get altered.

**Comment by alexellis** [comment]
I believe @JockDaRock was waiting on this change.

**Comment by alexellis** [comment]
@JockDaRock @kars7e merged in 0.6.14 if you'd like to try it along with the binary download option in the UI.

**Pull request merged**
