### PR TITLE
Added a blog to the blog section in community.md

### PR DESCRIPTION
**Pull request by staal-it**
Added a new blog entry to the community file

## Description

Added a new blog entry to the community file

## Types of changes

Signed-off-by: Erwin Staal <info@staal-it.nl>

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for sending your blog. There is no need to close your request just follow the instructions given by the bot. (in my Tweet to you I mentioned reading the contribution guide, is there something we can do to make it more obvious what you have to do?)

**Comment by staal-it** [comment]
No, this was just me... I did my first commit, signed it, did another commit and forgot to sign that one. Then I ran into some errors trying to sign it off and push the that. I closed the pr because I didn't want to wast your time.

**Comment by alexellis** [comment]
Hope you got there in the end. Just let us know on Slack if you need anything.

**Comment by staal-it** [comment]
I'll close this one, see #1190

**Pull request closed without merging**
