### PR TITLE
Add OpenFaaS in the VMware ecosystem - Webinar  Signed-off-by: Scott Rosenberg scott@tera-sky.com

### PR DESCRIPTION
**Pull request by vrabbi**
## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by vrabbi** [comment]
@rgee0 does this PR look ok?

**Comment by alexellis** [comment]
The commit message isn't done right. There should be a subject with the body being the sign off.

**Comment by alexellis** [comment]
Richard should be able to give you a quick git command to run to resolve. Thanks both

**Comment by zeerorg** [comment]
Can you run : 
```bash
git commit --amend -m \
"Add OpenFaaS in the VMware ecosystem - Webinar

Signed-off-by: Scott Rosenberg scott@tera-sky.com"

git push -f
```

This should resolve the issue

**Comment by zeerorg** [comment]
Please can you remove the "Signed-off-by: Scott Rosenberg scott@tera-sky.com" from the title, and instead add it in the description. Checkout this PR https://github.com/openfaas/faas/pull/1136 as an example

**Pull request closed without merging**
