### PR TITLE
Use functions.json instead of store-arch.json

### PR DESCRIPTION
**Pull request by zeerorg**
Moved to functions.json instead of store.json

## Motivation and Context
Fixes issue #1145 

## How Has This Been Tested?
The pull request has been pushed to zeerorg/gateway:new_store docker image.
In the `docker-compose.yml` change the gateway image from `openfaas/gateway:v0.13.0` to `zeerorg/gateway:new_store` then deploy to test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by zeerorg** [comment]
Derek add label: Review

**Comment by zeerorg** [comment]
Derek remove label: Review

**Comment by alexellis** [comment]
Please confirm there was no regression on armhf

**Comment by alexellis** [comment]
@zeerorg

**Comment by alexellis** [comment]
Derek set milestone: 0.13.0

**Comment by alexellis** [comment]
Derek set milestone: 0.13.0

**Comment by zeerorg** [comment]
Works fine with rapsberry pi
image

**Comment by zeerorg** [comment]
@alexellis PTAL

**Comment by alexellis** [comment]
Merged. Thank you

**Pull request merged**
