### PR TITLE
Feature for probing functions

### PR DESCRIPTION
**Pull request by alexellis**
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alex@openfaas.com>

## Description

Feature for probing functions

Introduces a single-flight call to a function's health endpoint to verify that it is registered with an Istio sidecar (Envoy) before letting the invocation through.

Results are cached for 5 seconds, before a probe is required again.

As explained in the linked issue, this is only required for Istio users, and is unrelated to Kubernetes' readiness probes. This specifically solves a race condition where the Envoy sidecar has not yet detected any endpoints for a function, but Kubernetes has done.

## Motivation and Context

Fixes: #1721 for Istio users.

## How Has This Been Tested?

Tested without Istio, with probe_functions environment variable set to true, I saw a probe execute in the logs.

The cache showed an expiry happening every 5 seconds and a re-probe occurring. A potential way to expand this work is to keep the probe cache valid so long as functions are being invoked without a 503 status, but this could lead to very complex code and interactions between components.

This is enabled through the environment variable `probe_functions=true` and a test image is available as: `docker.io/alexellis2/gateway:pb8`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

A separate change to the helm chart will be required to introduce the configuration variable.

Overall the changeset is artificially large, due to having to move some code and its tests into a common location.

### CODE REVIEW

**Comment by alexellis** [comment]
@kevin-lindsay-1 PTAL

**Comment by kevin-lindsay-1** [comment]
LGTM

**Comment by alexellis** [comment]
Thanks for confirming, I'll get this into the next release for you.

**Comment by kevin-lindsay-1** [comment]
@alexellis please let me know when this is available in the `faas-netes` chart, and I'll update posthaste.

**Comment by alexellis** [comment]
It will be available within the next few hours, keep an eye on the chart or faas-netes repo.

**Pull request merged**
