### PR TITLE
update read/write timeout config in seconds

### PR DESCRIPTION
**Pull request by viveksyngh**
Signed-off-by: Vivek Singh <vivekkmr45@yahoo.in>

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
@viveksyngh I've released https://github.com/openfaas/faas/releases/tag/0.7.1 - as soon as a new image is pushed we can merge your PR. Thank you for helping with this

**Comment by viveksyngh** [comment]
@alexellis Thanks, I have updated this PR to use 0.7.1.  I am still working on to validate whether faas-swarm is working fine with go durations.

**Comment by viveksyngh** [comment]
@alexellis  I looked at faas-swarm seems like we are passing the environment variable for `read_timeout` and 'write_timeout` config in `docker-comose.yml` file but we are not reading that config. We are using 10 as a default value [here](https://github.com/openfaas/faas-swarm/blob/9f928a6cfde2376fc18247acdc0033d0647b42d0/server.go#L54)

**Comment by alexellis** [comment]
@viveksyngh I didn't realise that.. we should fix it up asap.

**Comment by alexellis** [comment]
I'll take this one

**Comment by alexellis** [comment]
Please do that and check the of-watchdog too to make sure that it does too.

**Comment by viveksyngh** [comment]
@alex I have raised a pull request for faas watchdog here. https://github.com/openfaas/faas/pull/540/

I also checked for `of-watchdog`, We are only supporting `go duration` here https://github.com/openfaas-incubator/of-watchdog/blob/ab49a4b45520ecd40a782cf7c5b5a3ae4c03d157/config/config.go#L85

But in `README.md` we have mentioned that these configurations are in `seconds`. Should we change it to support integer values as well or update the documentation?

**Pull request merged**
