### PR TITLE
[Needs testing] Bump Golang version to 1.9.4

### PR DESCRIPTION
**Pull request by itscaro**
Update Docker image to 1.9.4, gateway arm64 is already on 1.9

### CODE REVIEW

**Comment by rgee0** [comment]
May as well include armhf as well as per #509

**Comment by alexellis** [comment]
@itscaro this cannot be merged because:

* No testing appears to have been done or shared in the PR
* The template isn't filled in

PTAL

**Comment by alexellis** [comment]
Ping @itscaro

**Comment by alexellis** [comment]
Pinging @itscaro can you do a quick test on this to verify it builds / runs as expected?

We have to have some context on PRs.

**Comment by alexellis** [comment]
Closed due to inactivity.

**Pull request closed without merging**
