### PR TITLE
updated hubstats to accept repo for pull count

### LINKED ISSUE #561: Sample function: Update/extend DockerHubStats
## Expected Behaviour

When given a username the function gives the amount of repositories for that username or org.

i.e.

```
%s has %d repositories on the Docker Hub
```

If a username and repo combo is given `username/repo`:

```
Repo: %s has been pulled %d times from the Docker Hub
```

## Current Behaviour

Only supports a username or org to count the repos available.

## Context

The API for fetching image pull statistics is here:

https://hub.docker.com/v2/repositories/functions/gateway/

Code is available here and can be built with the faas-cli

https://github.com/openfaas/faas/tree/master/sample-functions/DockerHubStats

```
cd faas/sample-functions
faas build --filter=dockerhubstats
```

### PR DESCRIPTION
**Pull request by BurtonR**
Signed-off-by: Burton Rheutan <rheutan7@gmail.com>

## Description

Resolves #561 
Updated hubstats sample function to accept repository input (`username/repository`) that will return the pull count

Also, separated the call to the docker api and parsing the response to make it easier to add more information to either request/response later on (stars, etc).

## Motivation and Context

- [X] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

Using PWD, deployed function and used `burtonr` and `burtonr/movies` as input. Validated response with the information displayed on Docker Hub

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [X] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Looks good - @rgee0 can you review?

**Comment by BurtonR** [comment]
@rgee0, I made the update to catch and handle the error from unmarsal. Is that what you were looking for?

**Comment by rgee0** [comment]
@BurtonR exactly that thanks.

**Comment by alexellis** [comment]
Thanks Burton - excited to see you getting commits into the project. Richard thank you for the review.

**Pull request merged**
