### PR TITLE
Add link to Crystal Template

### PR DESCRIPTION
**Pull request by TPei**
Signed-off-by: TPei <t.s.peikert@gmail.com>

I added a link to my crystal template repository

Not sure if this is still wanted since there hasn't been much activity in the list, but ¯\\_(ツ)_/¯

### CODE REVIEW

**Comment by ivanayov** [comment]
Thanks @TPei 
Updates are still active and appreciated :)

**Comment by alexellis** [comment]
Would be good to have someone take a look and review the approach before merging.

**Comment by TPei** [comment]
thoughts? @alexellis :)

**Comment by alexellis** [comment]
Unable to merge due to your merge commit, please amend your commits or create a new PR for this change:

> This branch cannot be rebased due to conflicts

Alex

**Pull request closed without merging**
